import type { Language } from "./types";

export type AtlasEditorSection =
  | "administrative"
  | "contact"
  | "operations"
  | "emergency"
  | "health"
  | "education"
  | "transport"
  | "hospitality"
  | "commerce"
  | "business"
  | "culture"
  | "tourism"
  | "leisure"
  | "infrastructure"
  | "industry"
  | "residential"
  | "technology"
  | "border";

export type AtlasTaxonomyLabel = { ku: string; ar: string; en: string };

export type AtlasTaxonomyGroup = {
  id: string;
  label: AtlasTaxonomyLabel;
  sections: readonly AtlasEditorSection[];
};

export type AtlasTaxonomyEntry = {
  id: string;
  group: string;
  label: AtlasTaxonomyLabel;
  aliases: readonly string[];
};
export const ATLAS_TAXONOMY_GROUPS = [
  { id: "settlement_admin", label: { ku: "شوێن و بەشە کارگێڕییەکان", ar: "الأماكن والتقسيمات الإدارية", en: "Settlements & administration" }, sections: ["administrative", "contact"] },
  { id: "government_public", label: { ku: "حکومەت و خزمەتگوزاری گشتی", ar: "الحكومة والخدمات العامة", en: "Government & public services" }, sections: ["contact", "operations"] },
  { id: "emergency_security", label: { ku: "فریاکەوتن و ئاسایش", ar: "الطوارئ والأمن", en: "Emergency & security" }, sections: ["contact", "operations", "emergency"] },
  { id: "health", label: { ku: "تەندروستی", ar: "الصحة", en: "Healthcare" }, sections: ["contact", "operations", "health"] },
  { id: "education_research", label: { ku: "پەروەردە و زانست", ar: "التعليم والبحث", en: "Education & research" }, sections: ["contact", "operations", "education"] },
  { id: "transport_logistics", label: { ku: "هاتووچۆ و لۆجستیک", ar: "النقل والخدمات اللوجستية", en: "Transport & logistics" }, sections: ["contact", "operations", "transport"] },
  { id: "food_hospitality", label: { ku: "خواردن و میوانداری", ar: "الطعام والضيافة", en: "Food & hospitality" }, sections: ["contact", "operations", "hospitality"] },
  { id: "retail_commerce", label: { ku: "بازرگانی و فرۆشتن", ar: "التجارة والتجزئة", en: "Retail & commerce" }, sections: ["contact", "operations", "commerce"] },
  { id: "finance_professional", label: { ku: "دارایی و خزمەتگوزاری پیشەیی", ar: "المالية والخدمات المهنية", en: "Finance & professional services" }, sections: ["contact", "operations", "business"] },
  { id: "culture_religion_media", label: { ku: "کولتوور و ئاین و میدیا", ar: "الثقافة والدين والإعلام", en: "Culture, religion & media" }, sections: ["contact", "operations", "culture"] },
  { id: "tourism_nature_heritage", label: { ku: "گەشتیاری و سروشت و میرات", ar: "السياحة والطبيعة والتراث", en: "Tourism, nature & heritage" }, sections: ["operations", "tourism"] },
  { id: "sports_leisure", label: { ku: "وەرزش و کات بەسەربردن", ar: "الرياضة والترفيه", en: "Sports & leisure" }, sections: ["contact", "operations", "leisure"] },
  { id: "utilities_infrastructure", label: { ku: "ژێرخان و خزمەتگوزارییە بنەڕەتییەکان", ar: "البنية التحتية والمرافق", en: "Utilities & infrastructure" }, sections: ["operations", "infrastructure"] },
  { id: "industry_agriculture", label: { ku: "پیشەسازی و کشتوکاڵ", ar: "الصناعة والزراعة", en: "Industry & agriculture" }, sections: ["contact", "operations", "industry"] },
  { id: "residential_buildings", label: { ku: "نیشتەجێبوون و بیناسازی", ar: "السكن والمباني", en: "Residential & buildings" }, sections: ["residential"] },
  { id: "communications_technology", label: { ku: "پەیوەندی و تەکنەلۆژیا", ar: "الاتصالات والتقنية", en: "Communications & technology" }, sections: ["contact", "operations", "technology"] },
  { id: "border_route", label: { ku: "سنوور و ڕێڕەوی گواستنەوە", ar: "الحدود ومسارات الحركة", en: "Borders & movement" }, sections: ["operations", "transport", "border"] },
] as const satisfies readonly AtlasTaxonomyGroup[];

export const ATLAS_TAXONOMY = [
  { id: "city", group: "settlement_admin", label: { ku: "شار", ar: "مدينة", en: "City" }, aliases: ["city", "شار", "مدينة"] },
  { id: "town", group: "settlement_admin", label: { ku: "شارۆچکە", ar: "بلدة", en: "Town" }, aliases: ["town", "بلدة", "شارۆچکە"] },
  { id: "village", group: "settlement_admin", label: { ku: "گوند", ar: "قرية", en: "Village" }, aliases: ["village", "قرية", "گوند"] },
  { id: "hamlet", group: "settlement_admin", label: { ku: "گوندۆکە", ar: "تجمع صغير", en: "Hamlet" }, aliases: ["hamlet", "تجمع صغير", "گوندۆکە"] },
  { id: "locality", group: "settlement_admin", label: { ku: "شوێنی ناوخۆیی", ar: "موقع محلي", en: "Locality" }, aliases: ["locality", "شوێنی ناوخۆیی", "موقع محلي"] },
  { id: "neighbourhood", group: "settlement_admin", label: { ku: "گەڕەک", ar: "حي", en: "Neighbourhood" }, aliases: ["neighbourhood", "حي", "گەڕەک"] },
  { id: "suburb", group: "settlement_admin", label: { ku: "پاشکۆی شار", ar: "ضاحية", en: "Suburb" }, aliases: ["suburb", "ضاحية", "پاشکۆی شار"] },
  { id: "district", group: "settlement_admin", label: { ku: "قەزا", ar: "قضاء", en: "District" }, aliases: ["district", "قضاء", "قەزا"] },
  { id: "subdistrict", group: "settlement_admin", label: { ku: "ناحیە", ar: "ناحية", en: "Subdistrict" }, aliases: ["subdistrict", "ناحية", "ناحیە"] },
  { id: "governorate", group: "settlement_admin", label: { ku: "پارێزگا", ar: "محافظة", en: "Governorate" }, aliases: ["governorate", "محافظة", "پارێزگا"] },
  { id: "region", group: "settlement_admin", label: { ku: "هەرێم", ar: "إقليم", en: "Region" }, aliases: ["region", "إقليم", "هەرێم"] },
  { id: "municipality", group: "settlement_admin", label: { ku: "شارەوانی", ar: "بلدية", en: "Municipality" }, aliases: ["municipality", "بلدية", "شارەوانی"] },
  { id: "ward", group: "settlement_admin", label: { ku: "بەشی شارەوانی", ar: "قطاع بلدي", en: "Municipal ward" }, aliases: ["municipal ward", "ward", "بەشی شارەوانی", "قطاع بلدي"] },
  { id: "quarter", group: "settlement_admin", label: { ku: "کەرت", ar: "محلة", en: "Quarter" }, aliases: ["quarter", "محلة", "کەرت"] },
  { id: "administrative_center", group: "settlement_admin", label: { ku: "ناوەندی کارگێڕی", ar: "مركز إداري", en: "Administrative centre" }, aliases: ["administrative center", "administrative centre", "administrative_center", "مركز إداري", "ناوەندی کارگێڕی"] },
  { id: "refugee_camp", group: "settlement_admin", label: { ku: "کەمپی پەنابەران", ar: "مخيم لاجئين", en: "Refugee camp" }, aliases: ["refugee camp", "refugee_camp", "مخيم لاجئين", "کەمپی پەنابەران"] },
  { id: "idp_camp", group: "settlement_admin", label: { ku: "کەمپی ئاوارەکان", ar: "مخيم نازحين", en: "IDP camp" }, aliases: ["idp camp", "idp_camp", "مخيم نازحين", "کەمپی ئاوارەکان"] },
  { id: "settlement", group: "settlement_admin", label: { ku: "نیشتەجێبوون", ar: "تجمع سكني", en: "Settlement" }, aliases: ["settlement", "تجمع سكني", "نیشتەجێبوون"] },
  { id: "industrial_town", group: "settlement_admin", label: { ku: "شارۆچکەی پیشەسازی", ar: "مدينة صناعية", en: "Industrial town" }, aliases: ["industrial town", "industrial_town", "شارۆچکەی پیشەسازی", "مدينة صناعية"] },
  { id: "new_town", group: "settlement_admin", label: { ku: "شارۆچکەی نوێ", ar: "مدينة جديدة", en: "New town" }, aliases: ["new town", "new_town", "شارۆچکەی نوێ", "مدينة جديدة"] },
  { id: "ministry", group: "government_public", label: { ku: "وەزارەت", ar: "وزارة", en: "Ministry" }, aliases: ["ministry", "وزارة", "وەزارەت"] },
  { id: "government_directorate", group: "government_public", label: { ku: "بەڕێوەبەرایەتی حکومی", ar: "مديرية حكومية", en: "Government directorate" }, aliases: ["government directorate", "government_directorate", "بەڕێوەبەرایەتی حکومی", "مديرية حكومية"] },
  { id: "general_directorate", group: "government_public", label: { ku: "بەڕێوەبەرایەتی گشتی", ar: "مديرية عامة", en: "General directorate" }, aliases: ["general directorate", "general_directorate", "بەڕێوەبەرایەتی گشتی", "مديرية عامة"] },
  { id: "government_office", group: "government_public", label: { ku: "نوسینگەی حکومی", ar: "مكتب حكومي", en: "Government office" }, aliases: ["government office", "government_office", "مكتب حكومي", "نوسینگەی حکومی"] },
  { id: "governor_office", group: "government_public", label: { ku: "نوسینگەی پارێزگار", ar: "ديوان المحافظة", en: "Governor office" }, aliases: ["governor office", "governor_office", "ديوان المحافظة", "نوسینگەی پارێزگار"] },
  { id: "mayor_office", group: "government_public", label: { ku: "نوسینگەی شارەوان", ar: "مكتب العمدة", en: "Mayor office" }, aliases: ["mayor office", "mayor_office", "مكتب العمدة", "نوسینگەی شارەوان"] },
  { id: "district_office", group: "government_public", label: { ku: "قایمقامێتی", ar: "قائمقامية", en: "District administration" }, aliases: ["district administration", "district office", "district_office", "قائمقامية", "قایمقامێتی"] },
  { id: "subdistrict_office", group: "government_public", label: { ku: "بەڕێوەبەرایەتی ناحیە", ar: "إدارة ناحية", en: "Subdistrict administration" }, aliases: ["subdistrict administration", "subdistrict office", "subdistrict_office", "إدارة ناحية", "بەڕێوەبەرایەتی ناحیە"] },
  { id: "parliament", group: "government_public", label: { ku: "پەرلەمان", ar: "برلمان", en: "Parliament" }, aliases: ["parliament", "برلمان", "پەرلەمان"] },
  { id: "court", group: "government_public", label: { ku: "دادگا", ar: "محكمة", en: "Court" }, aliases: ["court", "دادگا", "محكمة"] },
  { id: "prosecutor_office", group: "government_public", label: { ku: "دادستانی", ar: "ادعاء عام", en: "Prosecutor office" }, aliases: ["prosecutor office", "prosecutor_office", "ادعاء عام", "دادستانی"] },
  { id: "notary", group: "government_public", label: { ku: "نوسینگەی دادنووس", ar: "كاتب عدل", en: "Notary" }, aliases: ["notary", "كاتب عدل", "نوسینگەی دادنووس"] },
  { id: "civil_registry", group: "government_public", label: { ku: "تۆماری مەدەنی", ar: "الأحوال المدنية", en: "Civil registry" }, aliases: ["civil registry", "civil_registry", "الأحوال المدنية", "تۆماری مەدەنی"] },
  { id: "passport_office", group: "government_public", label: { ku: "نوسینگەی پاسپۆرت", ar: "مكتب الجوازات", en: "Passport office" }, aliases: ["passport office", "passport_office", "مكتب الجوازات", "نوسینگەی پاسپۆرت"] },
  { id: "identity_office", group: "government_public", label: { ku: "نوسینگەی کارت نیشتیمانی", ar: "مكتب الهوية الوطنية", en: "Identity office" }, aliases: ["identity office", "identity_office", "مكتب الهوية الوطنية", "نوسینگەی کارت نیشتیمانی"] },
  { id: "land_registry", group: "government_public", label: { ku: "تۆماری خانووبەرە", ar: "التسجيل العقاري", en: "Land registry" }, aliases: ["land registry", "land_registry", "التسجيل العقاري", "تۆماری خانووبەرە"] },
  { id: "tax_office", group: "government_public", label: { ku: "فەرمانگەی باج", ar: "دائرة الضرائب", en: "Tax office" }, aliases: ["tax office", "tax_office", "دائرة الضرائب", "فەرمانگەی باج"] },
  { id: "customs_office", group: "government_public", label: { ku: "گومرگ", ar: "جمارك", en: "Customs office" }, aliases: ["customs office", "customs_office", "جمارك", "گومرگ"] },
  { id: "social_security_office", group: "government_public", label: { ku: "نوسینگەی بیمەی کۆمەڵایەتی", ar: "الضمان الاجتماعي", en: "Social security office" }, aliases: ["social security office", "social_security_office", "الضمان الاجتماعي", "نوسینگەی بیمەی کۆمەڵایەتی"] },
  { id: "pension_office", group: "government_public", label: { ku: "نوسینگەی خانەنشینی", ar: "دائرة التقاعد", en: "Pension office" }, aliases: ["pension office", "pension_office", "دائرة التقاعد", "نوسینگەی خانەنشینی"] },
  { id: "public_service_center", group: "government_public", label: { ku: "ناوەندی خزمەتگوزاری گشتی", ar: "مركز خدمات عامة", en: "Public service centre" }, aliases: ["public service center", "public service centre", "public_service_center", "مركز خدمات عامة", "ناوەندی خزمەتگوزاری گشتی"] },
  { id: "election_office", group: "government_public", label: { ku: "نوسینگەی هەڵبژاردن", ar: "مكتب الانتخابات", en: "Election office" }, aliases: ["election office", "election_office", "مكتب الانتخابات", "نوسینگەی هەڵبژاردن"] },
  { id: "statistics_office", group: "government_public", label: { ku: "نوسینگەی ئامار", ar: "مكتب الإحصاء", en: "Statistics office" }, aliases: ["statistics office", "statistics_office", "مكتب الإحصاء", "نوسینگەی ئامار"] },
  { id: "planning_office", group: "government_public", label: { ku: "نوسینگەی پلان", ar: "مكتب التخطيط", en: "Planning office" }, aliases: ["planning office", "planning_office", "مكتب التخطيط", "نوسینگەی پلان"] },
  { id: "environment_office", group: "government_public", label: { ku: "نوسینگەی ژینگە", ar: "مكتب البيئة", en: "Environment office" }, aliases: ["environment office", "environment_office", "مكتب البيئة", "نوسینگەی ژینگە"] },
  { id: "agriculture_directorate", group: "government_public", label: { ku: "بەڕێوەبەرایەتی کشتوکاڵ", ar: "مديرية الزراعة", en: "Agriculture directorate" }, aliases: ["agriculture directorate", "agriculture_directorate", "بەڕێوەبەرایەتی کشتوکاڵ", "مديرية الزراعة"] },
  { id: "water_directorate", group: "government_public", label: { ku: "بەڕێوەبەرایەتی ئاو", ar: "مديرية الماء", en: "Water directorate" }, aliases: ["water directorate", "water_directorate", "بەڕێوەبەرایەتی ئاو", "مديرية الماء"] },
  { id: "electricity_directorate", group: "government_public", label: { ku: "بەڕێوەبەرایەتی کارەبا", ar: "مديرية الكهرباء", en: "Electricity directorate" }, aliases: ["electricity directorate", "electricity_directorate", "بەڕێوەبەرایەتی کارەبا", "مديرية الكهرباء"] },
  { id: "education_directorate", group: "government_public", label: { ku: "بەڕێوەبەرایەتی پەروەردە", ar: "مديرية التربية", en: "Education directorate" }, aliases: ["education directorate", "education_directorate", "بەڕێوەبەرایەتی پەروەردە", "مديرية التربية"] },
  { id: "health_directorate", group: "government_public", label: { ku: "بەڕێوەبەرایەتی تەندروستی", ar: "مديرية الصحة", en: "Health directorate" }, aliases: ["health directorate", "health_directorate", "بەڕێوەبەرایەتی تەندروستی", "مديرية الصحة"] },
  { id: "police_station", group: "emergency_security", label: { ku: "بنکەی پۆلیس", ar: "مركز شرطة", en: "Police station" }, aliases: ["police station", "police_station", "بنکەی پۆلیس", "مركز شرطة"] },
  { id: "traffic_police", group: "emergency_security", label: { ku: "پۆلیسی هاتووچۆ", ar: "شرطة المرور", en: "Traffic police" }, aliases: ["traffic police", "traffic_police", "شرطة المرور", "پۆلیسی هاتووچۆ"] },
  { id: "security_office", group: "emergency_security", label: { ku: "بنکەی ئاسایش", ar: "مكتب الأمن", en: "Security office" }, aliases: ["security office", "security_office", "بنکەی ئاسایش", "مكتب الأمن"] },
  { id: "fire_station", group: "emergency_security", label: { ku: "بنکەی ئاگرکوژێنەوە", ar: "مركز إطفاء", en: "Fire station" }, aliases: ["fire station", "fire_station", "بنکەی ئاگرکوژێنەوە", "مركز إطفاء"] },
  { id: "civil_defence", group: "emergency_security", label: { ku: "بەرگری مەدەنی", ar: "دفاع مدني", en: "Civil defence" }, aliases: ["civil defence", "civil_defence", "بەرگری مەدەنی", "دفاع مدني"] },
  { id: "emergency_center", group: "emergency_security", label: { ku: "ناوەندی فریاکەوتن", ar: "مركز طوارئ", en: "Emergency centre" }, aliases: ["emergency center", "emergency centre", "emergency_center", "مركز طوارئ", "ناوەندی فریاکەوتن"] },
  { id: "ambulance_station", group: "emergency_security", label: { ku: "بنکەی ئەمبولانس", ar: "محطة إسعاف", en: "Ambulance station" }, aliases: ["ambulance station", "ambulance_station", "بنکەی ئەمبولانس", "محطة إسعاف"] },
  { id: "rescue_station", group: "emergency_security", label: { ku: "بنکەی رزگارکردن", ar: "مركز إنقاذ", en: "Rescue station" }, aliases: ["rescue station", "rescue_station", "بنکەی رزگارکردن", "مركز إنقاذ"] },
  { id: "prison", group: "emergency_security", label: { ku: "زیندان", ar: "سجن", en: "Prison" }, aliases: ["prison", "زیندان", "سجن"] },
  { id: "detention_center", group: "emergency_security", label: { ku: "ناوەندی ڕاگرتن", ar: "مركز احتجاز", en: "Detention centre" }, aliases: ["detention center", "detention centre", "detention_center", "مركز احتجاز", "ناوەندی ڕاگرتن"] },
  { id: "military_base", group: "emergency_security", label: { ku: "بنکەی سەربازی", ar: "قاعدة عسكرية", en: "Military base" }, aliases: ["military base", "military_base", "بنکەی سەربازی", "قاعدة عسكرية"] },
  { id: "military_checkpoint", group: "emergency_security", label: { ku: "چێکپۆینتی سەربازی", ar: "نقطة تفتيش عسكرية", en: "Military checkpoint" }, aliases: ["military checkpoint", "military_checkpoint", "نقطة تفتيش عسكرية", "چێکپۆینتی سەربازی"] },
  { id: "police_checkpoint", group: "emergency_security", label: { ku: "بازگەی پۆلیس", ar: "نقطة تفتيش للشرطة", en: "Police checkpoint" }, aliases: ["police checkpoint", "police_checkpoint", "بازگەی پۆلیس", "نقطة تفتيش للشرطة"] },
  { id: "checkpoint", group: "emergency_security", label: { ku: "چێکپۆینت", ar: "نقطة تفتيش", en: "Checkpoint" }, aliases: ["checkpoint", "نقطة تفتيش", "چێکپۆینت"] },
  { id: "border_guard", group: "emergency_security", label: { ku: "بنکەی پاسەوانی سنوور", ar: "حرس الحدود", en: "Border guard" }, aliases: ["border guard", "border_guard", "بنکەی پاسەوانی سنوور", "حرس الحدود"] },
  { id: "security_checkpoint", group: "emergency_security", label: { ku: "چێکپۆینتی ئاسایشی", ar: "نقطة تفتيش أمنية", en: "Security checkpoint" }, aliases: ["security checkpoint", "security_checkpoint", "نقطة تفتيش أمنية", "چێکپۆینتی ئاسایشی"] },
  { id: "emergency_phone", group: "emergency_security", label: { ku: "تەلەفۆنی فریاکەوتن", ar: "هاتف طوارئ", en: "Emergency phone" }, aliases: ["emergency phone", "emergency_phone", "تەلەفۆنی فریاکەوتن", "هاتف طوارئ"] },
  { id: "shelter", group: "emergency_security", label: { ku: "پەناگە", ar: "ملجأ", en: "Shelter" }, aliases: ["shelter", "ملجأ", "پەناگە"] },
  { id: "disaster_response_center", group: "emergency_security", label: { ku: "ناوەندی وەڵامدانەوەی کارەسات", ar: "مركز الاستجابة للكوارث", en: "Disaster response centre" }, aliases: ["disaster response center", "disaster response centre", "disaster_response_center", "مركز الاستجابة للكوارث", "ناوەندی وەڵامدانەوەی کارەسات"] },
  { id: "physiotherapy_center", group: "health", label: { ku: "ناوەندی فیزیۆتێراپی", ar: "مركز علاج طبيعي", en: "Physiotherapy centre" }, aliases: ["physiotherapy", "physiotherapy center", "physiotherapy centre", "physiotherapy_center", "ناوەندی فیزیۆتێراپی", "مركز علاج طبيعي"] },
  { id: "sports_medicine_clinic", group: "health", label: { ku: "کلینیکی پزیشکی وەرزشی", ar: "عيادة طب رياضي", en: "Sports medicine clinic" }, aliases: ["sports medicine", "sports medicine clinic", "sports_medicine_clinic", "کلینیکی پزیشکی وەرزشی", "عيادة طب رياضي"] },
  { id: "urgent_care", group: "health", label: { ku: "چاودێری پزیشکی خێرا", ar: "رعاية عاجلة", en: "Urgent care" }, aliases: ["urgent care", "urgent_care", "چاودێری پزیشکی خێرا", "رعاية عاجلة"] },
  { id: "hospital", group: "health", label: { ku: "نەخۆشخانە", ar: "مستشفى", en: "Hospital" }, aliases: ["hospital", "مستشفى", "نەخۆشخانە"] },
  { id: "private_hospital", group: "health", label: { ku: "نەخۆشخانەی تایبەت", ar: "مستشفى خاص", en: "Private hospital" }, aliases: ["private hospital", "private_hospital", "مستشفى خاص", "نەخۆشخانەی تایبەت"] },
  { id: "health_center", group: "health", label: { ku: "بنکەی تەندروستی", ar: "مركز صحي", en: "Health centre" }, aliases: ["health center", "health centre", "health_center", "بنکەی تەندروستی", "مركز صحي"] },
  { id: "primary_health_center", group: "health", label: { ku: "بنکەی سەرەتایی تەندروستی", ar: "مركز رعاية صحية أولية", en: "Primary health centre" }, aliases: ["primary health center", "primary health centre", "primary_health_center", "بنکەی سەرەتایی تەندروستی", "مركز رعاية صحية أولية"] },
  { id: "clinic", group: "health", label: { ku: "کلینیک", ar: "عيادة", en: "Clinic" }, aliases: ["clinic", "عيادة", "کلینیک"] },
  { id: "medical_center", group: "health", label: { ku: "ناوەندی پزیشکی", ar: "مركز طبي", en: "Medical centre" }, aliases: ["medical center", "medical centre", "medical_center", "مركز طبي", "ناوەندی پزیشکی"] },
  { id: "dentist", group: "health", label: { ku: "کلینیکی ددان", ar: "عيادة أسنان", en: "Dentist" }, aliases: ["dentist", "عيادة أسنان", "کلینیکی ددان"] },
  { id: "eye_clinic", group: "health", label: { ku: "کلینیکی چاو", ar: "عيادة عيون", en: "Eye clinic" }, aliases: ["eye clinic", "eye_clinic", "عيادة عيون", "کلینیکی چاو"] },
  { id: "maternity_clinic", group: "health", label: { ku: "کلینیکی دایک و منداڵ", ar: "عيادة أمومة وطفولة", en: "Maternity clinic" }, aliases: ["maternity clinic", "maternity_clinic", "عيادة أمومة وطفولة", "کلینیکی دایک و منداڵ"] },
  { id: "laboratory", group: "health", label: { ku: "تاقیگە", ar: "مختبر", en: "Laboratory" }, aliases: ["laboratory", "تاقیگە", "مختبر"] },
  { id: "radiology_center", group: "health", label: { ku: "ناوەندی تیشک", ar: "مركز أشعة", en: "Radiology centre" }, aliases: ["radiology center", "radiology centre", "radiology_center", "مركز أشعة", "ناوەندی تیشک"] },
  { id: "pharmacy", group: "health", label: { ku: "دەرمانخانە", ar: "صيدلية", en: "Pharmacy" }, aliases: ["pharmacy", "دەرمانخانە", "صيدلية"] },
  { id: "blood_bank", group: "health", label: { ku: "بانکی خوێن", ar: "بنك دم", en: "Blood bank" }, aliases: ["blood bank", "blood_bank", "بانکی خوێن", "بنك دم"] },
  { id: "dialysis_center", group: "health", label: { ku: "ناوەندی شۆردنەوەی گورچیلە", ar: "مركز غسيل كلى", en: "Dialysis centre" }, aliases: ["dialysis center", "dialysis centre", "dialysis_center", "مركز غسيل كلى", "ناوەندی شۆردنەوەی گورچیلە"] },
  { id: "rehabilitation_center", group: "health", label: { ku: "ناوەندی چاکسازی تەندروستی", ar: "مركز تأهيل", en: "Rehabilitation centre" }, aliases: ["rehabilitation center", "rehabilitation centre", "rehabilitation_center", "مركز تأهيل", "ناوەندی چاکسازی تەندروستی"] },
  { id: "mental_health_center", group: "health", label: { ku: "ناوەندی تەندروستی دەروونی", ar: "مركز صحة نفسية", en: "Mental health centre" }, aliases: ["mental health center", "mental health centre", "mental_health_center", "مركز صحة نفسية", "ناوەندی تەندروستی دەروونی"] },
  { id: "veterinary_clinic", group: "health", label: { ku: "کلینیکی ڤێتەرنەری", ar: "عيادة بيطرية", en: "Veterinary clinic" }, aliases: ["veterinary clinic", "veterinary_clinic", "عيادة بيطرية", "کلینیکی ڤێتەرنەری"] },
  { id: "nursing_home", group: "health", label: { ku: "خانەی بەساڵاچووان", ar: "دار رعاية المسنين", en: "Nursing home" }, aliases: ["nursing home", "nursing_home", "خانەی بەساڵاچووان", "دار رعاية المسنين"] },
  { id: "medical_supply", group: "health", label: { ku: "پێداویستی پزیشکی", ar: "مستلزمات طبية", en: "Medical supply" }, aliases: ["medical supply", "medical_supply", "مستلزمات طبية", "پێداویستی پزیشکی"] },
  { id: "public_health_office", group: "health", label: { ku: "نوسینگەی تەندروستی گشتی", ar: "مكتب الصحة العامة", en: "Public health office" }, aliases: ["public health office", "public_health_office", "مكتب الصحة العامة", "نوسینگەی تەندروستی گشتی"] },
  { id: "driving_school", group: "education_research", label: { ku: "قوتابخانەی شۆفێری", ar: "مدرسة تعليم قيادة", en: "Driving school" }, aliases: ["driving school", "driving_school", "قوتابخانەی شۆفێری", "مدرسة تعليم قيادة"] },
  { id: "music_school", group: "education_research", label: { ku: "قوتابخانەی میوزیک", ar: "مدرسة موسيقى", en: "Music school" }, aliases: ["music school", "music_school", "قوتابخانەی میوزیک", "مدرسة موسيقى"] },
  { id: "special_education_center", group: "education_research", label: { ku: "ناوەندی پەروەردەی تایبەت", ar: "مركز تربية خاصة", en: "Special education centre" }, aliases: ["special education center", "special education centre", "special_education_center", "ناوەندی پەروەردەی تایبەت", "مركز تربية خاصة"] },
  { id: "kindergarten", group: "education_research", label: { ku: "باخچەی ساوایان", ar: "روضة أطفال", en: "Kindergarten" }, aliases: ["kindergarten", "باخچەی ساوایان", "روضة أطفال"] },
  { id: "primary_school", group: "education_research", label: { ku: "قوتابخانەی سەرەتایی", ar: "مدرسة ابتدائية", en: "Primary school" }, aliases: ["primary school", "primary_school", "قوتابخانەی سەرەتایی", "مدرسة ابتدائية"] },
  { id: "secondary_school", group: "education_research", label: { ku: "قوتابخانەی ناوەندی", ar: "مدرسة متوسطة", en: "Secondary school" }, aliases: ["secondary school", "secondary_school", "قوتابخانەی ناوەندی", "مدرسة متوسطة"] },
  { id: "high_school", group: "education_research", label: { ku: "قوتابخانەی ئامادەیی", ar: "مدرسة إعدادية", en: "High school" }, aliases: ["high school", "high_school", "قوتابخانەی ئامادەیی", "مدرسة إعدادية"] },
  { id: "school", group: "education_research", label: { ku: "قوتابخانە", ar: "مدرسة", en: "School" }, aliases: ["school", "قوتابخانە", "مدرسة"] },
  { id: "vocational_school", group: "education_research", label: { ku: "قوتابخانەی پیشەیی", ar: "مدرسة مهنية", en: "Vocational school" }, aliases: ["vocational school", "vocational_school", "قوتابخانەی پیشەیی", "مدرسة مهنية"] },
  { id: "institute", group: "education_research", label: { ku: "پەیمانگا", ar: "معهد", en: "Institute" }, aliases: ["institute", "معهد", "پەیمانگا"] },
  { id: "college", group: "education_research", label: { ku: "کۆلێژ", ar: "كلية", en: "College" }, aliases: ["college", "كلية", "کۆلێژ"] },
  { id: "university", group: "education_research", label: { ku: "زانکۆ", ar: "جامعة", en: "University" }, aliases: ["university", "جامعة", "زانکۆ"] },
  { id: "research_center", group: "education_research", label: { ku: "ناوەندی توێژینەوە", ar: "مركز أبحاث", en: "Research centre" }, aliases: ["research center", "research centre", "research_center", "مركز أبحاث", "ناوەندی توێژینەوە"] },
  { id: "training_center", group: "education_research", label: { ku: "ناوەندی ڕاهێنان", ar: "مركز تدريب", en: "Training centre" }, aliases: ["training center", "training centre", "training_center", "مركز تدريب", "ناوەندی ڕاهێنان"] },
  { id: "language_school", group: "education_research", label: { ku: "پەیمانگای زمان", ar: "معهد لغات", en: "Language school" }, aliases: ["language school", "language_school", "معهد لغات", "پەیمانگای زمان"] },
  { id: "library", group: "education_research", label: { ku: "کتێبخانە", ar: "مكتبة", en: "Library" }, aliases: ["library", "مكتبة", "کتێبخانە"] },
  { id: "student_dormitory", group: "education_research", label: { ku: "خەوابگەی قوتابیان", ar: "سكن طلاب", en: "Student dormitory" }, aliases: ["student dormitory", "student_dormitory", "خەوابگەی قوتابیان", "سكن طلاب"] },
  { id: "science_center", group: "education_research", label: { ku: "ناوەندی زانست", ar: "مركز علوم", en: "Science centre" }, aliases: ["science center", "science centre", "science_center", "مركز علوم", "ناوەندی زانست"] },
  { id: "academy", group: "education_research", label: { ku: "ئەکادیمی", ar: "أكاديمية", en: "Academy" }, aliases: ["academy", "أكاديمية", "ئەکادیمی"] },
  { id: "street", group: "transport_logistics", label: { ku: "شەقام", ar: "شارع", en: "Street" }, aliases: ["street", "road", "avenue", "boulevard", "lane", "شەقام", "ڕێگا", "شارع", "طريق"] },
  { id: "bicycle_parking", group: "transport_logistics", label: { ku: "پارکینگی پاسکیل", ar: "موقف دراجات", en: "Bicycle parking" }, aliases: ["bicycle parking", "bicycle_parking", "bike parking", "پارکینگی پاسکیل", "موقف دراجات"] },
  { id: "motorcycle_parking", group: "transport_logistics", label: { ku: "پارکینگی ماتۆڕ", ar: "موقف دراجات نارية", en: "Motorcycle parking" }, aliases: ["motorcycle parking", "motorcycle_parking", "پارکینگی ماتۆڕ", "موقف دراجات نارية"] },
  { id: "parcel_locker", group: "transport_logistics", label: { ku: "سندوقی وەرگرتنی پاکەت", ar: "خزانة طرود", en: "Parcel locker" }, aliases: ["parcel locker", "parcel_locker", "سندوقی وەرگرتنی پاکەت", "خزانة طرود"] },
  { id: "vehicle_inspection_center", group: "transport_logistics", label: { ku: "ناوەندی پشکنینی ئۆتۆمبێل", ar: "مركز فحص مركبات", en: "Vehicle inspection centre" }, aliases: ["vehicle inspection center", "vehicle inspection centre", "vehicle_inspection_center", "ناوەندی پشکنینی ئۆتۆمبێل", "مركز فحص مركبات"] },
  { id: "airport", group: "transport_logistics", label: { ku: "فڕۆکەخانە", ar: "مطار", en: "Airport" }, aliases: ["airport", "فڕۆکەخانە", "مطار"] },
  { id: "heliport", group: "transport_logistics", label: { ku: "فڕۆکەخانەی هێلیکۆپتەر", ar: "مهبط مروحيات", en: "Heliport" }, aliases: ["heliport", "فڕۆکەخانەی هێلیکۆپتەر", "مهبط مروحيات"] },
  { id: "bus_station", group: "transport_logistics", label: { ku: "وێستگەی پاس", ar: "محطة حافلات", en: "Bus station" }, aliases: ["bus station", "bus_station", "محطة حافلات", "وێستگەی پاس"] },
  { id: "bus_stop", group: "transport_logistics", label: { ku: "وێستگەی پاس", ar: "موقف حافلات", en: "Bus stop" }, aliases: ["bus stop", "bus_stop", "موقف حافلات", "وێستگەی پاس"] },
  { id: "taxi_station", group: "transport_logistics", label: { ku: "وێستگەی تاکسی", ar: "موقف سيارات أجرة", en: "Taxi station" }, aliases: ["taxi station", "taxi_station", "موقف سيارات أجرة", "وێستگەی تاکسی"] },
  { id: "garage", group: "transport_logistics", label: { ku: "گاراژ", ar: "كراج", en: "Garage" }, aliases: ["garage", "كراج", "گاراژ"] },
  { id: "parking", group: "transport_logistics", label: { ku: "پارکینگ", ar: "موقف سيارات", en: "Parking" }, aliases: ["parking", "موقف سيارات", "پارکینگ"] },
  { id: "parking_garage", group: "transport_logistics", label: { ku: "پارکینگی سەربەستراو", ar: "مرآب سيارات", en: "Parking garage" }, aliases: ["parking garage", "parking_garage", "مرآب سيارات", "پارکینگی سەربەستراو"] },
  { id: "fuel_station", group: "transport_logistics", label: { ku: "وێستگەی سووتەمەنی", ar: "محطة وقود", en: "Fuel station" }, aliases: ["fuel station", "fuel_station", "محطة وقود", "وێستگەی سووتەمەنی"] },
  { id: "ev_charging", group: "transport_logistics", label: { ku: "وێستگەی شەحنی ئۆتۆمبیلی کارەبایی", ar: "محطة شحن كهربائية", en: "EV charging station" }, aliases: ["ev charging", "ev charging station", "ev_charging", "محطة شحن كهربائية", "وێستگەی شەحنی ئۆتۆمبیلی کارەبایی"] },
  { id: "car_rental", group: "transport_logistics", label: { ku: "کرێی ئۆتۆمبیل", ar: "تأجير سيارات", en: "Car rental" }, aliases: ["car rental", "car_rental", "تأجير سيارات", "کرێی ئۆتۆمبیل"] },
  { id: "vehicle_inspection", group: "transport_logistics", label: { ku: "پشکنینی ئۆتۆمبیل", ar: "فحص مركبات", en: "Vehicle inspection" }, aliases: ["vehicle inspection", "vehicle_inspection", "فحص مركبات", "پشکنینی ئۆتۆمبیل"] },
  { id: "car_wash", group: "transport_logistics", label: { ku: "شۆردنەوەی ئۆتۆمبیل", ar: "غسيل سيارات", en: "Car wash" }, aliases: ["car wash", "car_wash", "شۆردنەوەی ئۆتۆمبیل", "غسيل سيارات"] },
  { id: "truck_stop", group: "transport_logistics", label: { ku: "وێستگەی کامیۆن", ar: "استراحة شاحنات", en: "Truck stop" }, aliases: ["truck stop", "truck_stop", "استراحة شاحنات", "وێستگەی کامیۆن"] },
  { id: "logistics_center", group: "transport_logistics", label: { ku: "ناوەندی لۆجستیک", ar: "مركز لوجستي", en: "Logistics centre" }, aliases: ["logistics center", "logistics centre", "logistics_center", "مركز لوجستي", "ناوەندی لۆجستیک"] },
  { id: "warehouse", group: "transport_logistics", label: { ku: "کۆگا", ar: "مستودع", en: "Warehouse" }, aliases: ["warehouse", "مستودع", "کۆگا"] },
  { id: "cargo_terminal", group: "transport_logistics", label: { ku: "تێرمیناڵی بار", ar: "محطة شحن", en: "Cargo terminal" }, aliases: ["cargo terminal", "cargo_terminal", "تێرمیناڵی بار", "محطة شحن"] },
  { id: "post_office", group: "transport_logistics", label: { ku: "پۆستە", ar: "مكتب بريد", en: "Post office" }, aliases: ["post office", "post_office", "مكتب بريد", "پۆستە"] },
  { id: "courier_service", group: "transport_logistics", label: { ku: "پۆست و گەیاندن", ar: "خدمة توصيل", en: "Courier service" }, aliases: ["courier service", "courier_service", "خدمة توصيل", "پۆست و گەیاندن"] },
  { id: "delivery_hub", group: "transport_logistics", label: { ku: "ناوەندی گەیاندن", ar: "مركز توصيل", en: "Delivery hub" }, aliases: ["delivery hub", "delivery_hub", "مركز توصيل", "ناوەندی گەیاندن"] },
  { id: "railway_station", group: "transport_logistics", label: { ku: "وێستگەی شەمەندەفەر", ar: "محطة قطار", en: "Railway station" }, aliases: ["railway station", "railway_station", "محطة قطار", "وێستگەی شەمەندەفەر"] },
  { id: "bridge", group: "transport_logistics", label: { ku: "پرد", ar: "جسر", en: "Bridge" }, aliases: ["bridge", "جسر", "پرد"] },
  { id: "tunnel", group: "transport_logistics", label: { ku: "تونێل", ar: "نفق", en: "Tunnel" }, aliases: ["tunnel", "تونێل", "نفق"] },
  { id: "ferry_terminal", group: "transport_logistics", label: { ku: "وێستگەی بەلەم", ar: "محطة عبّارة", en: "Ferry terminal" }, aliases: ["ferry terminal", "ferry_terminal", "محطة عبّارة", "وێستگەی بەلەم"] },
  { id: "restaurant", group: "food_hospitality", label: { ku: "چێشتخانە", ar: "مطعم", en: "Restaurant" }, aliases: ["restaurant", "مطعم", "چێشتخانە"] },
  { id: "kebab_restaurant", group: "food_hospitality", label: { ku: "کەبابخانە", ar: "مطعم كباب", en: "Kebab restaurant" }, aliases: ["kebab restaurant", "kebab_restaurant", "مطعم كباب", "کەبابخانە"] },
  { id: "fast_food", group: "food_hospitality", label: { ku: "خواردنی خێرا", ar: "وجبات سريعة", en: "Fast food" }, aliases: ["fast food", "fast_food", "خواردنی خێرا", "وجبات سريعة"] },
  { id: "cafe", group: "food_hospitality", label: { ku: "کافێ", ar: "مقهى", en: "Cafe" }, aliases: ["cafe", "مقهى", "کافێ"] },
  { id: "tea_house", group: "food_hospitality", label: { ku: "چایخانە", ar: "مقهى شاي", en: "Tea house" }, aliases: ["tea house", "tea_house", "مقهى شاي", "چایخانە"] },
  { id: "bakery", group: "food_hospitality", label: { ku: "نانەواخانە", ar: "مخبز", en: "Bakery" }, aliases: ["bakery", "مخبز", "نانەواخانە"] },
  { id: "pastry_shop", group: "food_hospitality", label: { ku: "شیرینی فرۆشی", ar: "حلويات", en: "Pastry shop" }, aliases: ["pastry shop", "pastry_shop", "حلويات", "شیرینی فرۆشی"] },
  { id: "juice_shop", group: "food_hospitality", label: { ku: "فرۆشگای شەربەت", ar: "محل عصائر", en: "Juice shop" }, aliases: ["juice shop", "juice_shop", "فرۆشگای شەربەت", "محل عصائر"] },
  { id: "ice_cream_shop", group: "food_hospitality", label: { ku: "فرۆشگای ئایسکرێم", ar: "محل مثلجات", en: "Ice cream shop" }, aliases: ["ice cream shop", "ice_cream_shop", "فرۆشگای ئایسکرێم", "محل مثلجات"] },
  { id: "food_court", group: "food_hospitality", label: { ku: "ناوەندی خواردن", ar: "ساحة طعام", en: "Food court" }, aliases: ["food court", "food_court", "ساحة طعام", "ناوەندی خواردن"] },
  { id: "hotel", group: "food_hospitality", label: { ku: "هۆتێل", ar: "فندق", en: "Hotel" }, aliases: ["hotel", "فندق", "هۆتێل"] },
  { id: "motel", group: "food_hospitality", label: { ku: "مۆتێل", ar: "نزل سيارات", en: "Motel" }, aliases: ["motel", "مۆتێل", "نزل سيارات"] },
  { id: "guest_house", group: "food_hospitality", label: { ku: "میوانخانە", ar: "بيت ضيافة", en: "Guest house" }, aliases: ["guest house", "guest_house", "بيت ضيافة", "میوانخانە"] },
  { id: "hostel", group: "food_hospitality", label: { ku: "هۆستێل", ar: "نزل", en: "Hostel" }, aliases: ["hostel", "نزل", "هۆستێل"] },
  { id: "resort", group: "food_hospitality", label: { ku: "ڕیزۆرت", ar: "منتجع", en: "Resort" }, aliases: ["resort", "منتجع", "ڕیزۆرت"] },
  { id: "wedding_hall", group: "food_hospitality", label: { ku: "هۆڵی ئاهەنگ", ar: "قاعة مناسبات", en: "Wedding hall" }, aliases: ["wedding hall", "wedding_hall", "قاعة مناسبات", "هۆڵی ئاهەنگ"] },
  { id: "banquet_hall", group: "food_hospitality", label: { ku: "هۆڵی میوانداری", ar: "قاعة ولائم", en: "Banquet hall" }, aliases: ["banquet hall", "banquet_hall", "قاعة ولائم", "هۆڵی میوانداری"] },
  { id: "catering_service", group: "food_hospitality", label: { ku: "خزمەتگوزاری خواردن", ar: "خدمة تموين", en: "Catering service" }, aliases: ["catering service", "catering_service", "خدمة تموين", "خزمەتگوزاری خواردن"] },
  { id: "market", group: "retail_commerce", label: { ku: "بازاڕ", ar: "سوق", en: "Market" }, aliases: ["market", "بازاڕ", "سوق"] },
  { id: "supermarket", group: "retail_commerce", label: { ku: "سۆپەرمارکێت", ar: "سوبرماركت", en: "Supermarket" }, aliases: ["supermarket", "سوبرماركت", "سۆپەرمارکێت"] },
  { id: "minimarket", group: "retail_commerce", label: { ku: "مینی مارکێت", ar: "ميني ماركت", en: "Minimarket" }, aliases: ["minimarket", "ميني ماركت", "مینی مارکێت"] },
  { id: "mall", group: "retail_commerce", label: { ku: "مەوڵ", ar: "مركز تجاري", en: "Mall" }, aliases: ["mall", "مركز تجاري", "مەوڵ"] },
  { id: "department_store", group: "retail_commerce", label: { ku: "فرۆشگای گەورە", ar: "متجر متعدد الأقسام", en: "Department store" }, aliases: ["department store", "department_store", "فرۆشگای گەورە", "متجر متعدد الأقسام"] },
  { id: "shop", group: "retail_commerce", label: { ku: "دوکان", ar: "متجر", en: "Shop" }, aliases: ["shop", "دوکان", "متجر"] },
  { id: "convenience_store", group: "retail_commerce", label: { ku: "دوکانی نزیک", ar: "متجر صغير", en: "Convenience store" }, aliases: ["convenience store", "convenience_store", "دوکانی نزیک", "متجر صغير"] },
  { id: "mobile_shop", group: "retail_commerce", label: { ku: "دوکانی مۆبایل", ar: "محل هواتف", en: "Mobile phone shop" }, aliases: ["mobile phone shop", "mobile shop", "mobile_shop", "دوکانی مۆبایل", "محل هواتف"] },
  { id: "electronics_shop", group: "retail_commerce", label: { ku: "فرۆشگای ئەلیکترۆنیات", ar: "متجر إلكترونيات", en: "Electronics shop" }, aliases: ["electronics shop", "electronics_shop", "فرۆشگای ئەلیکترۆنیات", "متجر إلكترونيات"] },
  { id: "computer_shop", group: "retail_commerce", label: { ku: "دوکانی کۆمپیوتەر", ar: "متجر حاسوب", en: "Computer shop" }, aliases: ["computer shop", "computer_shop", "دوکانی کۆمپیوتەر", "متجر حاسوب"] },
  { id: "clothes_shop", group: "retail_commerce", label: { ku: "جلوبەرگ فرۆشی", ar: "متجر ملابس", en: "Clothes shop" }, aliases: ["clothes shop", "clothes_shop", "جلوبەرگ فرۆشی", "متجر ملابس"] },
  { id: "shoes_shop", group: "retail_commerce", label: { ku: "پێڵاو فرۆشی", ar: "متجر أحذية", en: "Shoes shop" }, aliases: ["shoes shop", "shoes_shop", "متجر أحذية", "پێڵاو فرۆشی"] },
  { id: "jewelry_shop", group: "retail_commerce", label: { ku: "زێڕ فرۆشی", ar: "متجر مجوهرات", en: "Jewelry shop" }, aliases: ["jewelry shop", "jewelry_shop", "زێڕ فرۆشی", "متجر مجوهرات"] },
  { id: "cosmetics_shop", group: "retail_commerce", label: { ku: "کۆسمەتیک فرۆشی", ar: "متجر مستحضرات", en: "Cosmetics shop" }, aliases: ["cosmetics shop", "cosmetics_shop", "متجر مستحضرات", "کۆسمەتیک فرۆشی"] },
  { id: "furniture_shop", group: "retail_commerce", label: { ku: "کەل و پەلی ماڵ فرۆشی", ar: "متجر أثاث", en: "Furniture shop" }, aliases: ["furniture shop", "furniture_shop", "متجر أثاث", "کەل و پەلی ماڵ فرۆشی"] },
  { id: "hardware_shop", group: "retail_commerce", label: { ku: "کەلوپەلی بیناسازی", ar: "متجر أدوات", en: "Hardware shop" }, aliases: ["hardware shop", "hardware_shop", "متجر أدوات", "کەلوپەلی بیناسازی"] },
  { id: "building_materials", group: "retail_commerce", label: { ku: "کەرەستەی بیناسازی", ar: "مواد بناء", en: "Building materials" }, aliases: ["building materials", "building_materials", "مواد بناء", "کەرەستەی بیناسازی"] },
  { id: "bookshop", group: "retail_commerce", label: { ku: "کتێب فرۆشی", ar: "مكتبة لبيع الكتب", en: "Bookshop" }, aliases: ["bookshop", "مكتبة لبيع الكتب", "کتێب فرۆشی"] },
  { id: "stationery_shop", group: "retail_commerce", label: { ku: "نووسینگە و کاغەز فرۆشی", ar: "قرطاسية", en: "Stationery shop" }, aliases: ["stationery shop", "stationery_shop", "قرطاسية", "نووسینگە و کاغەز فرۆشی"] },
  { id: "toy_shop", group: "retail_commerce", label: { ku: "یاری منداڵان فرۆشی", ar: "متجر ألعاب", en: "Toy shop" }, aliases: ["toy shop", "toy_shop", "متجر ألعاب", "یاری منداڵان فرۆشی"] },
  { id: "butcher", group: "retail_commerce", label: { ku: "گۆشت فرۆشی", ar: "ملحمة", en: "Butcher" }, aliases: ["butcher", "ملحمة", "گۆشت فرۆشی"] },
  { id: "greengrocer", group: "retail_commerce", label: { ku: "میوە و سەوزە فرۆشی", ar: "خضروات وفواكه", en: "Greengrocer" }, aliases: ["greengrocer", "خضروات وفواكه", "میوە و سەوزە فرۆشی"] },
  { id: "dairy_shop", group: "retail_commerce", label: { ku: "بەرهەمی شیر فرۆشی", ar: "ألبان", en: "Dairy shop" }, aliases: ["dairy shop", "dairy_shop", "ألبان", "بەرهەمی شیر فرۆشی"] },
  { id: "car_showroom", group: "retail_commerce", label: { ku: "پێشانگای ئۆتۆمبیل", ar: "معرض سيارات", en: "Car showroom" }, aliases: ["car showroom", "car_showroom", "معرض سيارات", "پێشانگای ئۆتۆمبیل"] },
  { id: "auto_parts", group: "retail_commerce", label: { ku: "پارچەی ئۆتۆمبیل", ar: "قطع غيار سيارات", en: "Auto parts" }, aliases: ["auto parts", "auto_parts", "قطع غيار سيارات", "پارچەی ئۆتۆمبیل"] },
  { id: "tyre_shop", group: "retail_commerce", label: { ku: "تایەر فرۆشی", ar: "متجر إطارات", en: "Tyre shop" }, aliases: ["tyre shop", "tyre_shop", "تایەر فرۆشی", "متجر إطارات"] },
  { id: "motorcycle_shop", group: "retail_commerce", label: { ku: "ماتۆڕ فرۆشی", ar: "متجر دراجات نارية", en: "Motorcycle shop" }, aliases: ["motorcycle shop", "motorcycle_shop", "ماتۆڕ فرۆشی", "متجر دراجات نارية"] },
  { id: "bicycle_shop", group: "retail_commerce", label: { ku: "پاسکیل فرۆشی", ar: "متجر دراجات", en: "Bicycle shop" }, aliases: ["bicycle shop", "bicycle_shop", "متجر دراجات", "پاسکیل فرۆشی"] },
  { id: "pet_shop", group: "retail_commerce", label: { ku: "دوکانی ئاژەڵ", ar: "متجر حيوانات", en: "Pet shop" }, aliases: ["pet shop", "pet_shop", "دوکانی ئاژەڵ", "متجر حيوانات"] },
  { id: "florist", group: "retail_commerce", label: { ku: "گوڵ فرۆشی", ar: "محل زهور", en: "Florist" }, aliases: ["florist", "محل زهور", "گوڵ فرۆشی"] },
  { id: "gift_shop", group: "retail_commerce", label: { ku: "دیاری فرۆشی", ar: "متجر هدايا", en: "Gift shop" }, aliases: ["gift shop", "gift_shop", "دیاری فرۆشی", "متجر هدايا"] },
  { id: "farm_supply_shop", group: "retail_commerce", label: { ku: "پێداویستی کشتوکاڵ", ar: "مستلزمات زراعية", en: "Farm supply shop" }, aliases: ["farm supply shop", "farm_supply_shop", "مستلزمات زراعية", "پێداویستی کشتوکاڵ"] },
  { id: "appliance_shop", group: "retail_commerce", label: { ku: "کەلوپەلی کارەبایی", ar: "أجهزة منزلية", en: "Appliance shop" }, aliases: ["appliance shop", "appliance_shop", "أجهزة منزلية", "کەلوپەلی کارەبایی"] },
  { id: "carpet_shop", group: "retail_commerce", label: { ku: "فەرش فرۆشی", ar: "متجر سجاد", en: "Carpet shop" }, aliases: ["carpet shop", "carpet_shop", "فەرش فرۆشی", "متجر سجاد"] },
  { id: "optician", group: "retail_commerce", label: { ku: "عەینەک فرۆشی", ar: "بصريات", en: "Optician" }, aliases: ["optician", "بصريات", "عەینەک فرۆشی"] },
  { id: "bank", group: "finance_professional", label: { ku: "بانک", ar: "مصرف", en: "Bank" }, aliases: ["bank", "بانک", "مصرف"] },
  { id: "atm", group: "finance_professional", label: { ku: "خۆپارێز", ar: "صراف آلي", en: "ATM" }, aliases: ["atm", "خۆپارێز", "صراف آلي"] },
  { id: "payment_agent", group: "finance_professional", label: { ku: "ناوەندی پارەدان", ar: "وكيل دفع", en: "Payment agent" }, aliases: ["payment agent", "payment_agent", "وكيل دفع", "ناوەندی پارەدان"] },
  { id: "fastpay_agent", group: "finance_professional", label: { ku: "فاست‌پەی", ar: "فاست باي", en: "FastPay agent" }, aliases: ["FastPay", "fast pay", "fastpay_agent", "فاست‌پەی", "فاست باي"] },
  { id: "money_transfer", group: "finance_professional", label: { ku: "گواستنەوەی پارە", ar: "تحويل أموال", en: "Money transfer" }, aliases: ["money transfer", "money_transfer", "تحويل أموال", "گواستنەوەی پارە"] },
  { id: "currency_exchange", group: "finance_professional", label: { ku: "گۆڕینی دراو", ar: "صرافة", en: "Currency exchange" }, aliases: ["currency exchange", "currency_exchange", "صرافة", "گۆڕینی دراو"] },
  { id: "insurance_office", group: "finance_professional", label: { ku: "نوسینگەی بیمە", ar: "مكتب تأمين", en: "Insurance office" }, aliases: ["insurance office", "insurance_office", "مكتب تأمين", "نوسینگەی بیمە"] },
  { id: "microfinance", group: "finance_professional", label: { ku: "دارایی بچووک", ar: "تمويل صغير", en: "Microfinance" }, aliases: ["microfinance", "تمويل صغير", "دارایی بچووک"] },
  { id: "real_estate", group: "finance_professional", label: { ku: "عەقارات", ar: "عقارات", en: "Real estate" }, aliases: ["real estate", "real_estate", "عقارات", "عەقارات"] },
  { id: "law_office", group: "finance_professional", label: { ku: "نوسینگەی پارێزەر", ar: "مكتب محاماة", en: "Law office" }, aliases: ["law office", "law_office", "مكتب محاماة", "نوسینگەی پارێزەر"] },
  { id: "accounting_office", group: "finance_professional", label: { ku: "نوسینگەی ژمێریاری", ar: "مكتب محاسبة", en: "Accounting office" }, aliases: ["accounting office", "accounting_office", "مكتب محاسبة", "نوسینگەی ژمێریاری"] },
  { id: "consulting_office", group: "finance_professional", label: { ku: "نوسینگەی ڕاوێژکاری", ar: "مكتب استشارات", en: "Consulting office" }, aliases: ["consulting office", "consulting_office", "مكتب استشارات", "نوسینگەی ڕاوێژکاری"] },
  { id: "engineering_office", group: "finance_professional", label: { ku: "نوسینگەی ئەندازیاری", ar: "مكتب هندسي", en: "Engineering office" }, aliases: ["engineering office", "engineering_office", "مكتب هندسي", "نوسینگەی ئەندازیاری"] },
  { id: "architecture_office", group: "finance_professional", label: { ku: "نوسینگەی تەلارسازی", ar: "مكتب معماري", en: "Architecture office" }, aliases: ["architecture office", "architecture_office", "مكتب معماري", "نوسینگەی تەلارسازی"] },
  { id: "travel_agency", group: "finance_professional", label: { ku: "نوسینگەی گەشت", ar: "وكالة سفر", en: "Travel agency" }, aliases: ["travel agency", "travel_agency", "نوسینگەی گەشت", "وكالة سفر"] },
  { id: "employment_agency", group: "finance_professional", label: { ku: "نوسینگەی کار", ar: "مكتب توظيف", en: "Employment agency" }, aliases: ["employment agency", "employment_agency", "مكتب توظيف", "نوسینگەی کار"] },
  { id: "translation_office", group: "finance_professional", label: { ku: "نوسینگەی وەرگێڕان", ar: "مكتب ترجمة", en: "Translation office" }, aliases: ["translation office", "translation_office", "مكتب ترجمة", "نوسینگەی وەرگێڕان"] },
  { id: "advertising_agency", group: "finance_professional", label: { ku: "ئاجانسی ڕیکلام", ar: "وكالة إعلان", en: "Advertising agency" }, aliases: ["advertising agency", "advertising_agency", "ئاجانسی ڕیکلام", "وكالة إعلان"] },
  { id: "photography_studio", group: "finance_professional", label: { ku: "ستۆدیۆی وێنەگری", ar: "استوديو تصوير", en: "Photography studio" }, aliases: ["photography studio", "photography_studio", "استوديو تصوير", "ستۆدیۆی وێنەگری"] },
  { id: "printing_service", group: "finance_professional", label: { ku: "چاپخانە", ar: "مطبعة", en: "Printing service" }, aliases: ["printing service", "printing_service", "مطبعة", "چاپخانە"] },
  { id: "coworking_space", group: "finance_professional", label: { ku: "شوێنی هاوبەشی کار", ar: "مساحة عمل مشتركة", en: "Coworking space" }, aliases: ["coworking space", "coworking_space", "شوێنی هاوبەشی کار", "مساحة عمل مشتركة"] },
  { id: "company_headquarters", group: "finance_professional", label: { ku: "مەقەڕی کۆمپانیا", ar: "مقر شركة", en: "Company headquarters" }, aliases: ["company headquarters", "company_headquarters", "مقر شركة", "مەقەڕی کۆمپانیا"] },
  { id: "branch_office", group: "finance_professional", label: { ku: "لق", ar: "فرع", en: "Branch office" }, aliases: ["branch office", "branch_office", "فرع", "لق"] },
  { id: "mosque", group: "culture_religion_media", label: { ku: "مزگەوت", ar: "مسجد", en: "Mosque" }, aliases: ["mosque", "مزگەوت", "مسجد"] },
  { id: "church", group: "culture_religion_media", label: { ku: "کەلیسای مەسیحی", ar: "كنيسة مسيحية", en: "Church" }, aliases: ["church", "كنيسة مسيحية", "کەلیسای مەسیحی"] },
  { id: "synagogue", group: "culture_religion_media", label: { ku: "کەنیشت", ar: "كنيس", en: "Synagogue" }, aliases: ["synagogue", "كنيس", "کەنیشت"] },
  { id: "temple", group: "culture_religion_media", label: { ku: "پەرستگا", ar: "معبد", en: "Temple" }, aliases: ["temple", "معبد", "پەرستگا"] },
  { id: "religious_site", group: "culture_religion_media", label: { ku: "شوێنی ئایینی", ar: "موقع ديني", en: "Religious site" }, aliases: ["religious site", "religious_site", "شوێنی ئایینی", "موقع ديني"] },
  { id: "shrine", group: "culture_religion_media", label: { ku: "زیارەتگا", ar: "مزار", en: "Shrine" }, aliases: ["shrine", "زیارەتگا", "مزار"] },
  { id: "cemetery", group: "culture_religion_media", label: { ku: "قەبرستان", ar: "مقبرة", en: "Cemetery" }, aliases: ["cemetery", "قەبرستان", "مقبرة"] },
  { id: "museum", group: "culture_religion_media", label: { ku: "مۆزەخانە", ar: "متحف", en: "Museum" }, aliases: ["museum", "متحف", "مۆزەخانە"] },
  { id: "art_gallery", group: "culture_religion_media", label: { ku: "گەلەری هونەر", ar: "معرض فني", en: "Art gallery" }, aliases: ["art gallery", "art_gallery", "معرض فني", "گەلەری هونەر"] },
  { id: "cultural_center", group: "culture_religion_media", label: { ku: "ناوەندی کولتووری", ar: "مركز ثقافي", en: "Cultural centre" }, aliases: ["cultural center", "cultural centre", "cultural_center", "مركز ثقافي", "ناوەندی کولتووری"] },
  { id: "theatre", group: "culture_religion_media", label: { ku: "شانۆ", ar: "مسرح", en: "Theatre" }, aliases: ["theatre", "شانۆ", "مسرح"] },
  { id: "cinema", group: "culture_religion_media", label: { ku: "سینەما", ar: "سينما", en: "Cinema" }, aliases: ["cinema", "سينما", "سینەما"] },
  { id: "festival_ground", group: "culture_religion_media", label: { ku: "شوێنی فێستیڤاڵ", ar: "ساحة مهرجان", en: "Festival ground" }, aliases: ["festival ground", "festival_ground", "ساحة مهرجان", "شوێنی فێستیڤاڵ"] },
  { id: "monument", group: "culture_religion_media", label: { ku: "پەیکەر", ar: "نصب", en: "Monument" }, aliases: ["monument", "نصب", "پەیکەر"] },
  { id: "memorial", group: "culture_religion_media", label: { ku: "یادەوەری", ar: "نصب تذكاري", en: "Memorial" }, aliases: ["memorial", "نصب تذكاري", "یادەوەری"] },
  { id: "archaeological_site", group: "culture_religion_media", label: { ku: "شوێنی شوێنەوار", ar: "موقع أثري", en: "Archaeological site" }, aliases: ["archaeological site", "archaeological_site", "شوێنی شوێنەوار", "موقع أثري"] },
  { id: "castle", group: "culture_religion_media", label: { ku: "قەڵا", ar: "قلعة", en: "Castle" }, aliases: ["castle", "قلعة", "قەڵا"] },
  { id: "heritage_house", group: "culture_religion_media", label: { ku: "ماڵی میراتی", ar: "بيت تراثي", en: "Heritage house" }, aliases: ["heritage house", "heritage_house", "بيت تراثي", "ماڵی میراتی"] },
  { id: "television_station", group: "culture_religion_media", label: { ku: "تەلەڤزیۆن", ar: "محطة تلفزيون", en: "Television station" }, aliases: ["television station", "television_station", "تەلەڤزیۆن", "محطة تلفزيون"] },
  { id: "radio_station", group: "culture_religion_media", label: { ku: "ڕادیۆ ستەیشن", ar: "محطة إذاعة", en: "Radio station" }, aliases: ["radio station", "radio_station", "محطة إذاعة", "ڕادیۆ ستەیشن"] },
  { id: "newspaper_office", group: "culture_religion_media", label: { ku: "نوسینگەی ڕۆژنامە", ar: "مكتب صحيفة", en: "Newspaper office" }, aliases: ["newspaper office", "newspaper_office", "مكتب صحيفة", "نوسینگەی ڕۆژنامە"] },
  { id: "media_center", group: "culture_religion_media", label: { ku: "ناوەندی میدیا", ar: "مركز إعلامي", en: "Media centre" }, aliases: ["media center", "media centre", "media_center", "مركز إعلامي", "ناوەندی میدیا"] },
  { id: "community_center", group: "culture_religion_media", label: { ku: "ناوەندی کۆمەڵایەتی", ar: "مركز مجتمعي", en: "Community centre" }, aliases: ["community center", "community centre", "community_center", "مركز مجتمعي", "ناوەندی کۆمەڵایەتی"] },
  { id: "event_venue", group: "culture_religion_media", label: { ku: "شوێنی بۆنە", ar: "مكان فعاليات", en: "Event venue" }, aliases: ["event venue", "event_venue", "شوێنی بۆنە", "مكان فعاليات"] },
  { id: "tourist_attraction", group: "tourism_nature_heritage", label: { ku: "شوێنی گەشتیاری", ar: "معلم سياحي", en: "Tourist attraction" }, aliases: ["tourist attraction", "tourist_attraction", "شوێنی گەشتیاری", "معلم سياحي"] },
  { id: "tourist_information", group: "tourism_nature_heritage", label: { ku: "زانیاری گەشتیاری", ar: "معلومات سياحية", en: "Tourist information" }, aliases: ["tourist information", "tourist_information", "زانیاری گەشتیاری", "معلومات سياحية"] },
  { id: "viewpoint", group: "tourism_nature_heritage", label: { ku: "شوێنی سەیران", ar: "نقطة مشاهدة", en: "Viewpoint" }, aliases: ["viewpoint", "شوێنی سەیران", "نقطة مشاهدة"] },
  { id: "hiking_trailhead", group: "tourism_nature_heritage", label: { ku: "دەستپێکی ڕێڕەوی پیاسە", ar: "بداية مسار مشي", en: "Hiking trailhead" }, aliases: ["hiking trailhead", "hiking_trailhead", "trailhead", "دەستپێکی ڕێڕەوی پیاسە", "بداية مسار مشي"] },
  { id: "climbing_area", group: "tourism_nature_heritage", label: { ku: "ناوچەی شاخەوانی", ar: "منطقة تسلق", en: "Climbing area" }, aliases: ["climbing area", "climbing_area", "ناوچەی شاخەوانی", "منطقة تسلق"] },
  { id: "mountain", group: "tourism_nature_heritage", label: { ku: "شاخ", ar: "جبل", en: "Mountain" }, aliases: ["mountain", "جبل", "شاخ"] },
  { id: "peak", group: "tourism_nature_heritage", label: { ku: "لوتکە", ar: "قمة", en: "Peak" }, aliases: ["peak", "قمة", "لوتکە"] },
  { id: "hill", group: "tourism_nature_heritage", label: { ku: "گرد", ar: "تل", en: "Hill" }, aliases: ["hill", "تل", "گرد"] },
  { id: "valley", group: "tourism_nature_heritage", label: { ku: "دۆڵ", ar: "وادٍ", en: "Valley" }, aliases: ["valley", "دۆڵ", "وادٍ"] },
  { id: "canyon", group: "tourism_nature_heritage", label: { ku: "تەنیشتگا", ar: "خانق", en: "Canyon" }, aliases: ["canyon", "تەنیشتگا", "خانق"] },
  { id: "river", group: "tourism_nature_heritage", label: { ku: "ڕووبار", ar: "نهر", en: "River" }, aliases: ["river", "نهر", "ڕووبار"] },
  { id: "stream", group: "tourism_nature_heritage", label: { ku: "جۆگە", ar: "جدول", en: "Stream" }, aliases: ["stream", "جدول", "جۆگە"] },
  { id: "lake", group: "tourism_nature_heritage", label: { ku: "دەریاچە", ar: "بحيرة", en: "Lake" }, aliases: ["lake", "بحيرة", "دەریاچە"] },
  { id: "reservoir", group: "tourism_nature_heritage", label: { ku: "بەنداوی ئاو", ar: "خزان مائي", en: "Reservoir" }, aliases: ["reservoir", "بەنداوی ئاو", "خزان مائي"] },
  { id: "waterfall", group: "tourism_nature_heritage", label: { ku: "ئاوشار", ar: "شلال", en: "Waterfall" }, aliases: ["waterfall", "ئاوشار", "شلال"] },
  { id: "spring", group: "tourism_nature_heritage", label: { ku: "کانی", ar: "نبع", en: "Spring" }, aliases: ["spring", "نبع", "کانی"] },
  { id: "cave", group: "tourism_nature_heritage", label: { ku: "ئەشکەوت", ar: "كهف", en: "Cave" }, aliases: ["cave", "ئەشکەوت", "كهف"] },
  { id: "forest", group: "tourism_nature_heritage", label: { ku: "دارستان", ar: "غابة", en: "Forest" }, aliases: ["forest", "دارستان", "غابة"] },
  { id: "woodland", group: "tourism_nature_heritage", label: { ku: "دارستانی بچووک", ar: "أحراج", en: "Woodland" }, aliases: ["woodland", "أحراج", "دارستانی بچووک"] },
  { id: "nature_reserve", group: "tourism_nature_heritage", label: { ku: "پارێزراوی سروشتی", ar: "محمية طبيعية", en: "Nature reserve" }, aliases: ["nature reserve", "nature_reserve", "محمية طبيعية", "پارێزراوی سروشتی"] },
  { id: "island", group: "tourism_nature_heritage", label: { ku: "دوورگە", ar: "جزيرة", en: "Island" }, aliases: ["island", "دوورگە", "جزيرة"] },
  { id: "national_park", group: "tourism_nature_heritage", label: { ku: "پارکی نیشتیمانی", ar: "حديقة وطنية", en: "National park" }, aliases: ["national park", "national_park", "حديقة وطنية", "پارکی نیشتیمانی"] },
  { id: "botanical_garden", group: "tourism_nature_heritage", label: { ku: "باخچەی ڕووەکی", ar: "حديقة نباتية", en: "Botanical garden" }, aliases: ["botanical garden", "botanical_garden", "باخچەی ڕووەکی", "حديقة نباتية"] },
  { id: "zoo", group: "tourism_nature_heritage", label: { ku: "باخچەی ئاژەڵان", ar: "حديقة حيوان", en: "Zoo" }, aliases: ["zoo", "باخچەی ئاژەڵان", "حديقة حيوان"] },
  { id: "picnic_site", group: "tourism_nature_heritage", label: { ku: "شوێنی پیکنیک", ar: "منطقة تنزه", en: "Picnic site" }, aliases: ["picnic site", "picnic_site", "شوێنی پیکنیک", "منطقة تنزه"] },
  { id: "camp_site", group: "tourism_nature_heritage", label: { ku: "کەمپینگ", ar: "مخيم", en: "Camp site" }, aliases: ["camp site", "camp_site", "مخيم", "کەمپینگ"] },
  { id: "caravan_site", group: "tourism_nature_heritage", label: { ku: "شوێنی کاراڤان", ar: "موقع كرفانات", en: "Caravan site" }, aliases: ["caravan site", "caravan_site", "شوێنی کاراڤان", "موقع كرفانات"] },
  { id: "cable_car", group: "tourism_nature_heritage", label: { ku: "تەلی کابڵ", ar: "تلفريك", en: "Cable car" }, aliases: ["cable car", "cable_car", "تلفريك", "تەلی کابڵ"] },
  { id: "dam", group: "tourism_nature_heritage", label: { ku: "بەنداوی ئاو", ar: "سد", en: "Dam" }, aliases: ["dam", "بەنداوی ئاو", "سد"] },
  { id: "beach", group: "tourism_nature_heritage", label: { ku: "کەناری ئاو", ar: "شاطئ", en: "Beach" }, aliases: ["beach", "شاطئ", "کەناری ئاو"] },
  { id: "wetland", group: "tourism_nature_heritage", label: { ku: "زەوی تەڕ", ar: "أرض رطبة", en: "Wetland" }, aliases: ["wetland", "أرض رطبة", "زەوی تەڕ"] },
  { id: "hot_spring", group: "tourism_nature_heritage", label: { ku: "کانی گەرم", ar: "نبع حار", en: "Hot spring" }, aliases: ["hot spring", "hot_spring", "نبع حار", "کانی گەرم"] },
  { id: "scenic_route", group: "tourism_nature_heritage", label: { ku: "ڕێگای دیمەنی", ar: "طريق سياحي", en: "Scenic route" }, aliases: ["scenic route", "scenic_route", "طريق سياحي", "ڕێگای دیمەنی"] },
  { id: "martial_arts_center", group: "sports_leisure", label: { ku: "ناوەندی هونەرە جەنگییەکان", ar: "مركز فنون قتالية", en: "Martial arts centre" }, aliases: ["martial arts center", "martial arts centre", "martial_arts_center", "dojo", "ناوەندی هونەرە جەنگییەکان", "مركز فنون قتالية"] },
  { id: "kung_fu", group: "sports_leisure", label: { ku: "کۆنگ فو", ar: "كونغ فو", en: "Kung fu" }, aliases: ["kung fu", "kung_fu", "کۆنگ فو", "كونغ فو"] },
  { id: "taekwondo", group: "sports_leisure", label: { ku: "تەکواندۆ", ar: "تايكوندو", en: "Taekwondo" }, aliases: ["taekwondo", "تەکواندۆ", "تايكوندو"] },
  { id: "karate", group: "sports_leisure", label: { ku: "کاراتێ", ar: "كاراتيه", en: "Karate" }, aliases: ["karate", "کاراتێ", "كاراتيه"] },
  { id: "jeet_kune_do", group: "sports_leisure", label: { ku: "جیت کون دۆ", ar: "جيت كون دو", en: "Jeet Kune Do" }, aliases: ["jeet kune do", "jeet_kune_do", "jkd", "جیت کون دۆ", "جيت كون دو"] },
  { id: "wushu", group: "sports_leisure", label: { ku: "ووشوو", ar: "ووشو", en: "Wushu" }, aliases: ["wushu", "ووشوو", "ووشو"] },
  { id: "shaolin_martial_arts", group: "sports_leisure", label: { ku: "هونەرە جەنگییەکانی شاولین", ar: "فنون شاولين القتالية", en: "Shaolin martial arts" }, aliases: ["shaolin", "shaolin martial arts", "shaolin_martial_arts", "شاولین", "فنون شاولين القتالية"] },
  { id: "parkour", group: "sports_leisure", label: { ku: "پارکۆر", ar: "باركور", en: "Parkour" }, aliases: ["parkour", "پارکۆر", "باركور"] },
  { id: "mma_gym", group: "sports_leisure", label: { ku: "یانەی هونەرە جەنگییە تێکەڵەکان", ar: "نادي فنون قتالية مختلطة", en: "MMA gym" }, aliases: ["mma", "mma gym", "mma_gym", "mixed martial arts", "هونەرە جەنگییە تێکەڵەکان", "فنون قتالية مختلطة"] },
  { id: "boxing_club", group: "sports_leisure", label: { ku: "یانەی بۆکس", ar: "نادي ملاكمة", en: "Boxing club" }, aliases: ["boxing", "boxing club", "boxing_club", "بۆکس", "نادي ملاكمة"] },
  { id: "kickboxing", group: "sports_leisure", label: { ku: "کیک بۆکسینگ", ar: "كيك بوكسينغ", en: "Kickboxing" }, aliases: ["kickboxing", "kick boxing", "کیک بۆکسینگ", "كيك بوكسينغ"] },
  { id: "muay_thai", group: "sports_leisure", label: { ku: "موی تای", ar: "مواي تاي", en: "Muay Thai" }, aliases: ["muay thai", "muay_thai", "موی تای", "مواي تاي"] },
  { id: "judo", group: "sports_leisure", label: { ku: "جودۆ", ar: "جودو", en: "Judo" }, aliases: ["judo", "جودۆ", "جودو"] },
  { id: "wrestling_club", group: "sports_leisure", label: { ku: "یانەی زۆرانبازی", ar: "نادي مصارعة", en: "Wrestling club" }, aliases: ["wrestling", "wrestling club", "wrestling_club", "زۆرانبازی", "نادي مصارعة"] },
  { id: "yoga_studio", group: "sports_leisure", label: { ku: "ستۆدیۆی یۆگا", ar: "استوديو يوغا", en: "Yoga studio" }, aliases: ["yoga", "yoga studio", "yoga_studio", "یۆگا", "استوديو يوغا"] },
  { id: "climbing_gym", group: "sports_leisure", label: { ku: "هۆڵی شاخەوانی", ar: "صالة تسلق", en: "Climbing gym" }, aliases: ["climbing gym", "climbing_gym", "indoor climbing", "هۆڵی شاخەوانی", "صالة تسلق"] },
  { id: "dance_studio", group: "sports_leisure", label: { ku: "ستۆدیۆی سەما", ar: "استوديو رقص", en: "Dance studio" }, aliases: ["dance studio", "dance_studio", "ستۆدیۆی سەما", "استوديو رقص"] },
  { id: "cycling_club", group: "sports_leisure", label: { ku: "یانەی پاسکیل‌سواری", ar: "نادي دراجات", en: "Cycling club" }, aliases: ["cycling club", "cycling_club", "bicycle club", "یانەی پاسکیل‌سواری", "نادي دراجات"] },
  { id: "stadium", group: "sports_leisure", label: { ku: "یاریگا", ar: "ملعب", en: "Stadium" }, aliases: ["stadium", "ملعب", "یاریگا"] },
  { id: "sports_center", group: "sports_leisure", label: { ku: "ناوەندی وەرزش", ar: "مركز رياضي", en: "Sports centre" }, aliases: ["sports center", "sports centre", "sports_center", "مركز رياضي", "ناوەندی وەرزش"] },
  { id: "football_field", group: "sports_leisure", label: { ku: "گۆڕەپانی تۆپێن", ar: "ملعب كرة قدم", en: "Football field" }, aliases: ["football field", "football_field", "ملعب كرة قدم", "گۆڕەپانی تۆپێن"] },
  { id: "basketball_court", group: "sports_leisure", label: { ku: "گۆڕەپانی باسکەتبۆڵ", ar: "ملعب كرة سلة", en: "Basketball court" }, aliases: ["basketball court", "basketball_court", "ملعب كرة سلة", "گۆڕەپانی باسکەتبۆڵ"] },
  { id: "volleyball_court", group: "sports_leisure", label: { ku: "گۆڕەپانی والیبال", ar: "ملعب كرة طائرة", en: "Volleyball court" }, aliases: ["volleyball court", "volleyball_court", "ملعب كرة طائرة", "گۆڕەپانی والیبال"] },
  { id: "tennis_court", group: "sports_leisure", label: { ku: "گۆڕەپانی تێنس", ar: "ملعب تنس", en: "Tennis court" }, aliases: ["tennis court", "tennis_court", "ملعب تنس", "گۆڕەپانی تێنس"] },
  { id: "gym", group: "sports_leisure", label: { ku: "جیم", ar: "صالة رياضية", en: "Gym" }, aliases: ["gym", "جیم", "صالة رياضية"] },
  { id: "swimming_pool", group: "sports_leisure", label: { ku: "مەسبەح", ar: "مسبح", en: "Swimming pool" }, aliases: ["swimming pool", "swimming_pool", "مسبح", "مەسبەح"] },
  { id: "playground", group: "sports_leisure", label: { ku: "یاری منداڵان", ar: "ملعب أطفال", en: "Playground" }, aliases: ["playground", "ملعب أطفال", "یاری منداڵان"] },
  { id: "park", group: "sports_leisure", label: { ku: "پارک", ar: "منتزه", en: "Park" }, aliases: ["park", "منتزه", "پارک"] },
  { id: "amusement_park", group: "sports_leisure", label: { ku: "پارکی یاری", ar: "مدينة ألعاب", en: "Amusement park" }, aliases: ["amusement park", "amusement_park", "مدينة ألعاب", "پارکی یاری"] },
  { id: "water_park", group: "sports_leisure", label: { ku: "پارکی ئاو", ar: "مدينة مائية", en: "Water park" }, aliases: ["water park", "water_park", "مدينة مائية", "پارکی ئاو"] },
  { id: "gaming_center", group: "sports_leisure", label: { ku: "گەیم سەنتەر", ar: "مركز ألعاب", en: "Gaming centre" }, aliases: ["gaming center", "gaming centre", "gaming_center", "مركز ألعاب", "گەیم سەنتەر"] },
  { id: "esports_center", group: "sports_leisure", label: { ku: "ناوەندی ئیسپۆرت", ar: "مركز رياضات إلكترونية", en: "Esports centre" }, aliases: ["esports center", "esports centre", "esports_center", "مركز رياضات إلكترونية", "ناوەندی ئیسپۆرت"] },
  { id: "bowling", group: "sports_leisure", label: { ku: "بۆڵینگ", ar: "بولينغ", en: "Bowling" }, aliases: ["bowling", "بولينغ", "بۆڵینگ"] },
  { id: "billiards_hall", group: "sports_leisure", label: { ku: "هۆڵی بلیارد", ar: "صالة بلياردو", en: "Billiards hall" }, aliases: ["billiards hall", "billiards_hall", "صالة بلياردو", "هۆڵی بلیارد"] },
  { id: "horse_club", group: "sports_leisure", label: { ku: "یانەی ئەسپسواری", ar: "نادي فروسية", en: "Horse club" }, aliases: ["horse club", "horse_club", "نادي فروسية", "یانەی ئەسپسواری"] },
  { id: "shooting_club", group: "sports_leisure", label: { ku: "یانەی نیشانەشکێنی", ar: "نادي رماية", en: "Shooting club" }, aliases: ["shooting club", "shooting_club", "نادي رماية", "یانەی نیشانەشکێنی"] },
  { id: "spa", group: "sports_leisure", label: { ku: "سپا", ar: "منتجع صحي", en: "Spa" }, aliases: ["spa", "سپا", "منتجع صحي"] },
  { id: "sauna", group: "sports_leisure", label: { ku: "ساونا", ar: "ساونا", en: "Sauna" }, aliases: ["sauna", "ساونا"] },
  { id: "fitness_trail", group: "sports_leisure", label: { ku: "ڕێڕەوی وەرزش", ar: "مسار لياقة", en: "Fitness trail" }, aliases: ["fitness trail", "fitness_trail", "مسار لياقة", "ڕێڕەوی وەرزش"] },
  { id: "race_track", group: "sports_leisure", label: { ku: "مەیدانی سیباق", ar: "حلبة سباق", en: "Race track" }, aliases: ["race track", "race_track", "حلبة سباق", "مەیدانی سیباق"] },
  { id: "power_station", group: "utilities_infrastructure", label: { ku: "وێزگەی کارەبا", ar: "محطة كهرباء", en: "Power station" }, aliases: ["power station", "power_station", "محطة كهرباء", "وێزگەی کارەبا"] },
  { id: "substation", group: "utilities_infrastructure", label: { ku: "وێستگەی گواستنەوەی کارەبا", ar: "محطة تحويل", en: "Electrical substation" }, aliases: ["electrical substation", "substation", "محطة تحويل", "وێستگەی گواستنەوەی کارەبا"] },
  { id: "power_plant", group: "utilities_infrastructure", label: { ku: "کارگەی بەرهەمهێنانی کارەبا", ar: "محطة توليد", en: "Power plant" }, aliases: ["power plant", "power_plant", "محطة توليد", "کارگەی بەرهەمهێنانی کارەبا"] },
  { id: "oil_field", group: "utilities_infrastructure", label: { ku: "کێڵگەی نەوت", ar: "حقل نفط", en: "Oil field" }, aliases: ["oil field", "oil_field", "حقل نفط", "کێڵگەی نەوت"] },
  { id: "oil_facility", group: "utilities_infrastructure", label: { ku: "وێزگەی نەوت", ar: "منشأة نفطية", en: "Oil facility" }, aliases: ["oil facility", "oil_facility", "منشأة نفطية", "وێزگەی نەوت"] },
  { id: "gas_station_facility", group: "utilities_infrastructure", label: { ku: "دەزگای گاز", ar: "منشأة غاز", en: "Gas facility" }, aliases: ["gas facility", "gas station facility", "gas_station_facility", "دەزگای گاز", "منشأة غاز"] },
  { id: "water_treatment", group: "utilities_infrastructure", label: { ku: "پاڵاوتنەوەی ئاو", ar: "معالجة مياه", en: "Water treatment" }, aliases: ["water treatment", "water_treatment", "معالجة مياه", "پاڵاوتنەوەی ئاو"] },
  { id: "wastewater_treatment", group: "utilities_infrastructure", label: { ku: "پاڵاوتنەوەی ئاوی پیس", ar: "معالجة مياه الصرف", en: "Wastewater treatment" }, aliases: ["wastewater treatment", "wastewater_treatment", "معالجة مياه الصرف", "پاڵاوتنەوەی ئاوی پیس"] },
  { id: "water_tower", group: "utilities_infrastructure", label: { ku: "بورجی ئاو", ar: "برج مياه", en: "Water tower" }, aliases: ["water tower", "water_tower", "برج مياه", "بورجی ئاو"] },
  { id: "reservoir_covered", group: "utilities_infrastructure", label: { ku: "خەزێنەی ئاو", ar: "خزان مياه", en: "Water reservoir" }, aliases: ["reservoir covered", "reservoir_covered", "water reservoir", "خزان مياه", "خەزێنەی ئاو"] },
  { id: "telecom_tower", group: "utilities_infrastructure", label: { ku: "بورجی پەیوەندی", ar: "برج اتصالات", en: "Telecom tower" }, aliases: ["telecom tower", "telecom_tower", "برج اتصالات", "بورجی پەیوەندی"] },
  { id: "communication_mast", group: "utilities_infrastructure", label: { ku: "مەستەی پەیوەندی", ar: "سارية اتصالات", en: "Communication mast" }, aliases: ["communication mast", "communication_mast", "سارية اتصالات", "مەستەی پەیوەندی"] },
  { id: "data_center", group: "utilities_infrastructure", label: { ku: "داتا سەنتەر", ar: "مركز بيانات", en: "Data centre" }, aliases: ["data center", "data centre", "data_center", "داتا سەنتەر", "مركز بيانات"] },
  { id: "recycling_center", group: "utilities_infrastructure", label: { ku: "ناوەندی ڕیسایکل", ar: "مركز تدوير", en: "Recycling centre" }, aliases: ["recycling center", "recycling centre", "recycling_center", "مركز تدوير", "ناوەندی ڕیسایکل"] },
  { id: "waste_transfer_station", group: "utilities_infrastructure", label: { ku: "وێستگەی گواستنەوەی پاشماوە", ar: "محطة نقل نفايات", en: "Waste transfer station" }, aliases: ["waste transfer station", "waste_transfer_station", "محطة نقل نفايات", "وێستگەی گواستنەوەی پاشماوە"] },
  { id: "landfill", group: "utilities_infrastructure", label: { ku: "شوێنی پاشماوە", ar: "مكب نفايات", en: "Landfill" }, aliases: ["landfill", "شوێنی پاشماوە", "مكب نفايات"] },
  { id: "water_pumping_station", group: "utilities_infrastructure", label: { ku: "وێستگەی پەمپی ئاو", ar: "محطة ضخ مياه", en: "Water pumping station" }, aliases: ["water pumping station", "water_pumping_station", "محطة ضخ مياه", "وێستگەی پەمپی ئاو"] },
  { id: "sewage_pumping_station", group: "utilities_infrastructure", label: { ku: "وێستگەی پەمپی ئاوی پیس", ar: "محطة ضخ صرف", en: "Sewage pumping station" }, aliases: ["sewage pumping station", "sewage_pumping_station", "محطة ضخ صرف", "وێستگەی پەمپی ئاوی پیس"] },
  { id: "road_maintenance_yard", group: "utilities_infrastructure", label: { ku: "ناوەندی چاکسازی ڕێگا", ar: "ساحة صيانة طرق", en: "Road maintenance yard" }, aliases: ["road maintenance yard", "road_maintenance_yard", "ساحة صيانة طرق", "ناوەندی چاکسازی ڕێگا"] },
  { id: "street_lighting_station", group: "utilities_infrastructure", label: { ku: "وێستگەی ڕووناکی شەقام", ar: "محطة إنارة", en: "Street lighting station" }, aliases: ["street lighting station", "street_lighting_station", "محطة إنارة", "وێستگەی ڕووناکی شەقام"] },
  { id: "solar_farm", group: "utilities_infrastructure", label: { ku: "کێڵگەی خۆرەتاو", ar: "مزرعة شمسية", en: "Solar farm" }, aliases: ["solar farm", "solar_farm", "مزرعة شمسية", "کێڵگەی خۆرەتاو"] },
  { id: "wind_farm", group: "utilities_infrastructure", label: { ku: "کێڵگەی با", ar: "مزرعة رياح", en: "Wind farm" }, aliases: ["wind farm", "wind_farm", "مزرعة رياح", "کێڵگەی با"] },
  { id: "transformer", group: "utilities_infrastructure", label: { ku: "گۆڕەری کارەبا", ar: "محولة كهرباء", en: "Transformer" }, aliases: ["transformer", "محولة كهرباء", "گۆڕەری کارەبا"] },
  { id: "water_well", group: "utilities_infrastructure", label: { ku: "بیری ئاو", ar: "بئر ماء", en: "Water well" }, aliases: ["water well", "water_well", "بئر ماء", "بیری ئاو"] },
  { id: "factory", group: "industry_agriculture", label: { ku: "کارگە", ar: "مصنع", en: "Factory" }, aliases: ["factory", "مصنع", "کارگە"] },
  { id: "workshop", group: "industry_agriculture", label: { ku: "وەرشە", ar: "ورشة", en: "Workshop" }, aliases: ["workshop", "ورشة", "وەرشە"] },
  { id: "industrial_zone", group: "industry_agriculture", label: { ku: "ناوچەی پیشەسازی", ar: "منطقة صناعية", en: "Industrial zone" }, aliases: ["industrial zone", "industrial_zone", "منطقة صناعية", "ناوچەی پیشەسازی"] },
  { id: "quarry", group: "industry_agriculture", label: { ku: "کانگا", ar: "مقلع", en: "Quarry" }, aliases: ["quarry", "مقلع", "کانگا"] },
  { id: "mine", group: "industry_agriculture", label: { ku: "معدەن", ar: "منجم", en: "Mine" }, aliases: ["mine", "معدەن", "منجم"] },
  { id: "cement_factory", group: "industry_agriculture", label: { ku: "کارگەی چیمەنتۆ", ar: "مصنع إسمنت", en: "Cement factory" }, aliases: ["cement factory", "cement_factory", "مصنع إسمنت", "کارگەی چیمەنتۆ"] },
  { id: "brick_factory", group: "industry_agriculture", label: { ku: "کارگەی خشت", ar: "مصنع طابوق", en: "Brick factory" }, aliases: ["brick factory", "brick_factory", "مصنع طابوق", "کارگەی خشت"] },
  { id: "food_factory", group: "industry_agriculture", label: { ku: "کارگەی خواردن", ar: "مصنع أغذية", en: "Food factory" }, aliases: ["food factory", "food_factory", "مصنع أغذية", "کارگەی خواردن"] },
  { id: "textile_factory", group: "industry_agriculture", label: { ku: "کارگەی قوماش", ar: "مصنع نسيج", en: "Textile factory" }, aliases: ["textile factory", "textile_factory", "مصنع نسيج", "کارگەی قوماش"] },
  { id: "cold_storage", group: "industry_agriculture", label: { ku: "کۆگای سارد", ar: "مخزن مبرد", en: "Cold storage" }, aliases: ["cold storage", "cold_storage", "مخزن مبرد", "کۆگای سارد"] },
  { id: "farm", group: "industry_agriculture", label: { ku: "کێڵگە", ar: "مزرعة", en: "Farm" }, aliases: ["farm", "مزرعة", "کێڵگە"] },
  { id: "farmland", group: "industry_agriculture", label: { ku: "زەوی کشتوکاڵی", ar: "أرض زراعية", en: "Farmland" }, aliases: ["farmland", "أرض زراعية", "زەوی کشتوکاڵی"] },
  { id: "orchard", group: "industry_agriculture", label: { ku: "باخ", ar: "بستان", en: "Orchard" }, aliases: ["orchard", "باخ", "بستان"] },
  { id: "greenhouse", group: "industry_agriculture", label: { ku: "گەرمخانە", ar: "بيت زجاجي", en: "Greenhouse" }, aliases: ["greenhouse", "بيت زجاجي", "گەرمخانە"] },
  { id: "livestock_farm", group: "industry_agriculture", label: { ku: "کێڵگەی ئاژەڵداری", ar: "مزرعة مواشي", en: "Livestock farm" }, aliases: ["livestock farm", "livestock_farm", "مزرعة مواشي", "کێڵگەی ئاژەڵداری"] },
  { id: "poultry_farm", group: "industry_agriculture", label: { ku: "کێڵگەی مریشک", ar: "مزرعة دواجن", en: "Poultry farm" }, aliases: ["poultry farm", "poultry_farm", "مزرعة دواجن", "کێڵگەی مریشک"] },
  { id: "fish_farm", group: "industry_agriculture", label: { ku: "کێڵگەی ماسی", ar: "مزرعة أسماك", en: "Fish farm" }, aliases: ["fish farm", "fish_farm", "مزرعة أسماك", "کێڵگەی ماسی"] },
  { id: "dairy_farm", group: "industry_agriculture", label: { ku: "کێڵگەی شیر", ar: "مزرعة ألبان", en: "Dairy farm" }, aliases: ["dairy farm", "dairy_farm", "مزرعة ألبان", "کێڵگەی شیر"] },
  { id: "grain_silo", group: "industry_agriculture", label: { ku: "سایلۆی دانەوێڵە", ar: "صومعة حبوب", en: "Grain silo" }, aliases: ["grain silo", "grain_silo", "سایلۆی دانەوێڵە", "صومعة حبوب"] },
  { id: "slaughterhouse", group: "industry_agriculture", label: { ku: "کۆشتارگە", ar: "مجزرة", en: "Slaughterhouse" }, aliases: ["slaughterhouse", "مجزرة", "کۆشتارگە"] },
  { id: "agricultural_cooperative", group: "industry_agriculture", label: { ku: "کۆمەڵەی کشتوکاڵی", ar: "تعاونية زراعية", en: "Agricultural cooperative" }, aliases: ["agricultural cooperative", "agricultural_cooperative", "تعاونية زراعية", "کۆمەڵەی کشتوکاڵی"] },
  { id: "irrigation_station", group: "industry_agriculture", label: { ku: "وێستگەی ئاودێری", ar: "محطة ري", en: "Irrigation station" }, aliases: ["irrigation station", "irrigation_station", "محطة ري", "وێستگەی ئاودێری"] },
  { id: "beekeeping", group: "industry_agriculture", label: { ku: "مێروولەداری", ar: "تربية نحل", en: "Beekeeping" }, aliases: ["beekeeping", "تربية نحل", "مێروولەداری"] },
  { id: "nursery", group: "industry_agriculture", label: { ku: "نەمامگە", ar: "مشتل", en: "Plant nursery" }, aliases: ["nursery", "plant nursery", "مشتل", "نەمامگە"] },
  { id: "sawmill", group: "industry_agriculture", label: { ku: "کارگەی تەختە", ar: "منشرة خشب", en: "Sawmill" }, aliases: ["sawmill", "منشرة خشب", "کارگەی تەختە"] },
  { id: "house", group: "residential_buildings", label: { ku: "ماڵ", ar: "منزل", en: "House" }, aliases: ["house", "ماڵ", "منزل"] },
  { id: "home", group: "residential_buildings", label: { ku: "خانوو", ar: "بيت", en: "Home" }, aliases: ["home", "بيت", "خانوو"] },
  { id: "apartment", group: "residential_buildings", label: { ku: "شوقە", ar: "شقة", en: "Apartment" }, aliases: ["apartment", "شقة", "شوقە"] },
  { id: "apartment_building", group: "residential_buildings", label: { ku: "بینای شوقە", ar: "عمارة سكنية", en: "Apartment building" }, aliases: ["apartment building", "apartment_building", "بینای شوقە", "عمارة سكنية"] },
  { id: "residential_compound", group: "residential_buildings", label: { ku: "کۆمپاوندی نیشتەجێبوون", ar: "مجمع سكني", en: "Residential compound" }, aliases: ["residential compound", "residential_compound", "مجمع سكني", "کۆمپاوندی نیشتەجێبوون"] },
  { id: "tower", group: "residential_buildings", label: { ku: "بورج", ar: "برج", en: "Tower" }, aliases: ["tower", "برج", "بورج"] },
  { id: "office_building", group: "residential_buildings", label: { ku: "بینای ئۆفیس", ar: "مبنى مكاتب", en: "Office building" }, aliases: ["office building", "office_building", "بینای ئۆفیس", "مبنى مكاتب"] },
  { id: "commercial_building", group: "residential_buildings", label: { ku: "بینای بازرگانی", ar: "مبنى تجاري", en: "Commercial building" }, aliases: ["commercial building", "commercial_building", "بینای بازرگانی", "مبنى تجاري"] },
  { id: "mixed_use_building", group: "residential_buildings", label: { ku: "بینای تێکەڵ", ar: "مبنى متعدد الاستخدام", en: "Mixed-use building" }, aliases: ["mixed use building", "mixed-use building", "mixed_use_building", "بینای تێکەڵ", "مبنى متعدد الاستخدام"] },
  { id: "villa", group: "residential_buildings", label: { ku: "ڤێلا", ar: "فيلا", en: "Villa" }, aliases: ["villa", "فيلا", "ڤێلا"] },
  { id: "farmhouse", group: "residential_buildings", label: { ku: "ماڵی کێڵگە", ar: "بيت ريفي", en: "Farmhouse" }, aliases: ["farmhouse", "بيت ريفي", "ماڵی کێڵگە"] },
  { id: "dormitory", group: "residential_buildings", label: { ku: "خەوابگە", ar: "سكن", en: "Dormitory" }, aliases: ["dormitory", "خەوابگە", "سكن"] },
  { id: "barracks", group: "residential_buildings", label: { ku: "بارەگا", ar: "ثكنة", en: "Barracks" }, aliases: ["barracks", "بارەگا", "ثكنة"] },
  { id: "cabin", group: "residential_buildings", label: { ku: "کەپر", ar: "كوخ", en: "Cabin" }, aliases: ["cabin", "كوخ", "کەپر"] },
  { id: "construction_site", group: "residential_buildings", label: { ku: "پڕۆژەی بیناسازی", ar: "موقع بناء", en: "Construction site" }, aliases: ["construction site", "construction_site", "موقع بناء", "پڕۆژەی بیناسازی"] },
  { id: "private_property", group: "residential_buildings", label: { ku: "موڵکی کەسی", ar: "ملكية خاصة", en: "Private property" }, aliases: ["private property", "private_property", "ملكية خاصة", "موڵکی کەسی"] },
  { id: "internet_provider", group: "communications_technology", label: { ku: "پڕۆڤایدەری ئینتەرنێت", ar: "مزود إنترنت", en: "Internet provider" }, aliases: ["internet provider", "internet_provider", "مزود إنترنت", "پڕۆڤایدەری ئینتەرنێت"] },
  { id: "telecom_office", group: "communications_technology", label: { ku: "نوسینگەی پەیوەندی", ar: "مكتب اتصالات", en: "Telecom office" }, aliases: ["telecom office", "telecom_office", "مكتب اتصالات", "نوسینگەی پەیوەندی"] },
  { id: "mobile_operator", group: "communications_technology", label: { ku: "کۆمپانیای مۆبایل", ar: "شركة اتصالات", en: "Mobile operator" }, aliases: ["mobile operator", "mobile_operator", "شركة اتصالات", "کۆمپانیای مۆبایل"] },
  { id: "korek_center", group: "communications_technology", label: { ku: "سەنتەری کۆڕەک", ar: "مركز كورك", en: "Korek centre" }, aliases: ["Korek", "Korek center", "korek_center", "سەنتەری کۆڕەک", "مركز كورك"] },
  { id: "asiacell_center", group: "communications_technology", label: { ku: "سەنتەری ئاسیاسێڵ", ar: "مركز آسياسيل", en: "Asiacell centre" }, aliases: ["Asiacell", "Asiacell center", "asiacell_center", "سەنتەری ئاسیاسێڵ", "مركز آسياسيل"] },
  { id: "zain_center", group: "communications_technology", label: { ku: "سەنتەری زەین", ar: "مركز زين", en: "Zain centre" }, aliases: ["Zain", "Zain center", "zain_center", "سەنتەری زەین", "مركز زين"] },
  { id: "korek_tower", group: "communications_technology", label: { ku: "بورجی کۆڕەک", ar: "برج كورك", en: "Korek tower" }, aliases: ["Korek tower", "korek_tower", "بورجی کۆڕەک", "برج كورك"] },
  { id: "asiacell_tower", group: "communications_technology", label: { ku: "بورجی ئاسیاسێڵ", ar: "برج آسياسيل", en: "Asiacell tower" }, aliases: ["Asiacell tower", "asiacell_tower", "بورجی ئاسیاسێڵ", "برج آسياسيل"] },
  { id: "zain_tower", group: "communications_technology", label: { ku: "بورجی زەین", ar: "برج زين", en: "Zain tower" }, aliases: ["Zain tower", "zain_tower", "بورجی زەین", "برج زين"] },
  { id: "internet_cafe", group: "communications_technology", label: { ku: "ئینتەرنێت کافێ", ar: "مقهى إنترنت", en: "Internet cafe" }, aliases: ["internet cafe", "internet_cafe", "ئینتەرنێت کافێ", "مقهى إنترنت"] },
  { id: "computer_service", group: "communications_technology", label: { ku: "خزمەتگوزاری کۆمپیوتەر", ar: "خدمة حاسوب", en: "Computer service" }, aliases: ["computer service", "computer_service", "خدمة حاسوب", "خزمەتگوزاری کۆمپیوتەر"] },
  { id: "phone_repair", group: "communications_technology", label: { ku: "چاککردنەوەی مۆبایل", ar: "تصليح هواتف", en: "Phone repair" }, aliases: ["phone repair", "phone_repair", "تصليح هواتف", "چاککردنەوەی مۆبایل"] },
  { id: "software_company", group: "communications_technology", label: { ku: "کۆمپانیای نەرمەواڵا", ar: "شركة برمجيات", en: "Software company" }, aliases: ["software company", "software_company", "شركة برمجيات", "کۆمپانیای نەرمەواڵا"] },
  { id: "technology_company", group: "communications_technology", label: { ku: "کۆمپانیای تەکنەلۆژیا", ar: "شركة تقنية", en: "Technology company" }, aliases: ["technology company", "technology_company", "شركة تقنية", "کۆمپانیای تەکنەلۆژیا"] },
  { id: "startup_hub", group: "communications_technology", label: { ku: "ناوەندی ستارتاپ", ar: "حاضنة أعمال", en: "Startup hub" }, aliases: ["startup hub", "startup_hub", "حاضنة أعمال", "ناوەندی ستارتاپ"] },
  { id: "broadcast_tower", group: "communications_technology", label: { ku: "بورجی پەخش", ar: "برج بث", en: "Broadcast tower" }, aliases: ["broadcast tower", "broadcast_tower", "برج بث", "بورجی پەخش"] },
  { id: "satellite_station", group: "communications_technology", label: { ku: "وێستگەی سەتەلایت", ar: "محطة أقمار صناعية", en: "Satellite station" }, aliases: ["satellite station", "satellite_station", "محطة أقمار صناعية", "وێستگەی سەتەلایت"] },
  { id: "postal_centre", group: "communications_technology", label: { ku: "ناوەندی پۆست", ar: "مركز بريد", en: "Postal centre" }, aliases: ["postal centre", "postal_centre", "مركز بريد", "ناوەندی پۆست"] },
  { id: "call_center", group: "communications_technology", label: { ku: "ناوەندی پەیوەندی", ar: "مركز اتصال", en: "Call centre" }, aliases: ["call center", "call centre", "call_center", "مركز اتصال", "ناوەندی پەیوەندی"] },
  { id: "maker_space", group: "communications_technology", label: { ku: "تاقیگەی دروستکردن", ar: "مساحة تصنيع", en: "Maker space" }, aliases: ["maker space", "maker_space", "تاقیگەی دروستکردن", "مساحة تصنيع"] },
  { id: "border_crossing", group: "border_route", label: { ku: "دەروازەی سنووری", ar: "منفذ حدودي", en: "Border crossing" }, aliases: ["border crossing", "border_crossing", "دەروازەی سنووری", "منفذ حدودي"] },
  { id: "international_border_crossing", group: "border_route", label: { ku: "دەروازەی نێودەوڵەتی", ar: "منفذ حدودي دولي", en: "International border crossing" }, aliases: ["international border crossing", "international_border_crossing", "دەروازەی نێودەوڵەتی", "منفذ حدودي دولي"] },
  { id: "internal_checkpoint", group: "border_route", label: { ku: "چێکپۆینتی ناوخۆیی", ar: "نقطة تفتيش داخلية", en: "Internal checkpoint" }, aliases: ["internal checkpoint", "internal_checkpoint", "نقطة تفتيش داخلية", "چێکپۆینتی ناوخۆیی"] },
  { id: "customs_checkpoint", group: "border_route", label: { ku: "چێکپۆینتی گومرگ", ar: "نقطة جمارك", en: "Customs checkpoint" }, aliases: ["customs checkpoint", "customs_checkpoint", "نقطة جمارك", "چێکپۆینتی گومرگ"] },
  { id: "toll_booth", group: "border_route", label: { ku: "دەروازەی باج", ar: "بوابة رسوم", en: "Toll booth" }, aliases: ["toll booth", "toll_booth", "بوابة رسوم", "دەروازەی باج"] },
  { id: "weigh_station", group: "border_route", label: { ku: "وێستگەی کێشکردنی ئۆتۆمبیل", ar: "محطة وزن", en: "Weigh station" }, aliases: ["weigh station", "weigh_station", "محطة وزن", "وێستگەی کێشکردنی ئۆتۆمبیل"] },
  { id: "mountain_pass", group: "border_route", label: { ku: "دەروازەی شاخ", ar: "ممر جبلي", en: "Mountain pass" }, aliases: ["mountain pass", "mountain_pass", "دەروازەی شاخ", "ممر جبلي"] },
  { id: "route_junction", group: "border_route", label: { ku: "دووڕێیان", ar: "تقاطع طرق", en: "Route junction" }, aliases: ["route junction", "route_junction", "تقاطع طرق", "دووڕێیان"] },
  { id: "highway_service_area", group: "border_route", label: { ku: "شوێنی خزمەتگوزاری ڕێگا", ar: "استراحة طريق", en: "Highway service area" }, aliases: ["highway service area", "highway_service_area", "استراحة طريق", "شوێنی خزمەتگوزاری ڕێگا"] },
  { id: "rest_area", group: "border_route", label: { ku: "شوێنی پشوودان", ar: "استراحة", en: "Rest area" }, aliases: ["rest area", "rest_area", "استراحة", "شوێنی پشوودان"] },
  { id: "bench", group: "sports_leisure", label: { ku: "کورسی دانیشتن", ar: "مقعد عام", en: "Bench" }, aliases: ["bench", "seat", "کورسی دانیشتن", "مقعد عام"] },
  { id: "public_art", group: "culture_religion_media", label: { ku: "هونەری گشتی", ar: "فن عام", en: "Public art" }, aliases: ["public art", "artwork", "هونەری گشتی", "فن عام"] },
  { id: "hair_salon", group: "retail_commerce", label: { ku: "سەرتاشخانە", ar: "صالون حلاقة", en: "Hair salon" }, aliases: ["hair salon", "hairdresser", "barber", "سەرتاشخانە", "صالون حلاقة"] },
  { id: "beauty_salon", group: "retail_commerce", label: { ku: "جوانکاری", ar: "صالون تجميل", en: "Beauty salon" }, aliases: ["beauty salon", "beauty shop", "جوانکاری", "صالون تجميل"] },
  { id: "sports_shop", group: "retail_commerce", label: { ku: "فرۆشگای کەلوپەلی وەرزشی", ar: "متجر رياضي", en: "Sports shop" }, aliases: ["sports shop", "sports store", "فرۆشگای کەلوپەلی وەرزشی", "متجر رياضي"] },
  { id: "waste_bin", group: "utilities_infrastructure", label: { ku: "سەتڵی پاشماوە", ar: "سلة نفايات", en: "Waste bin" }, aliases: ["waste bin", "waste basket", "سەتڵی پاشماوە", "سلة نفايات"] },
  { id: "fountain", group: "tourism_nature_heritage", label: { ku: "نافورە", ar: "نافورة", en: "Fountain" }, aliases: ["fountain", "نافورە", "نافورة"] },
  { id: "observation_tower", group: "tourism_nature_heritage", label: { ku: "بورجی چاودێری", ar: "برج مراقبة", en: "Observation tower" }, aliases: ["observation tower", "watch tower", "بورجی چاودێری", "برج مراقبة"] },
  { id: "surveillance_camera", group: "emergency_security", label: { ku: "کامێرای چاودێری", ar: "كاميرا مراقبة", en: "Surveillance camera" }, aliases: ["surveillance camera", "cctv", "speed camera", "radar camera", "کامێرای چاودێری", "كاميرا مراقبة", "رادار"] },
  { id: "bar", group: "food_hospitality", label: { ku: "بار", ar: "حانة", en: "Bar" }, aliases: ["bar", "بار", "حانة"] },
  { id: "public_toilet", group: "government_public", label: { ku: "ئاودەستی گشتی", ar: "مرحاض عام", en: "Public toilet" }, aliases: ["public toilet", "toilet", "wc", "ئاودەستی گشتی", "مرحاض عام"] },
  { id: "beverages_shop", group: "retail_commerce", label: { ku: "فرۆشگای خواردنەوە", ar: "متجر مشروبات", en: "Beverage shop" }, aliases: ["beverage shop", "beverages", "فرۆشگای خواردنەوە", "متجر مشروبات"] },
  { id: "kiosk", group: "retail_commerce", label: { ku: "کۆشک", ar: "كشك", en: "Kiosk" }, aliases: ["kiosk", "کۆشک", "كشك"] },
  { id: "pub", group: "food_hospitality", label: { ku: "پەب", ar: "حانة", en: "Pub" }, aliases: ["pub", "پەب", "حانة"] },
  { id: "laundry_service", group: "retail_commerce", label: { ku: "شۆردنەوەی جل", ar: "مغسلة ملابس", en: "Laundry service" }, aliases: ["laundry", "laundry service", "شۆردنەوەی جل", "مغسلة ملابس"] },
  { id: "public_telephone", group: "communications_technology", label: { ku: "تەلەفۆنی گشتی", ar: "هاتف عام", en: "Public telephone" }, aliases: ["public telephone", "telephone", "تەلەفۆنی گشتی", "هاتف عام"] },
  { id: "drinking_water", group: "utilities_infrastructure", label: { ku: "ئاوی خواردنەوە", ar: "مياه شرب", en: "Drinking water" }, aliases: ["drinking water", "potable water", "ئاوی خواردنەوە", "مياه شرب"] },
  { id: "outdoor_shop", group: "retail_commerce", label: { ku: "فرۆشگای کەلوپەلی دەرەوە", ar: "متجر مستلزمات خارجية", en: "Outdoor shop" }, aliases: ["outdoor shop", "outdoor store", "فرۆشگای کەلوپەلی دەرەوە", "متجر مستلزمات خارجية"] },
  { id: "consulate", group: "government_public", label: { ku: "کونسوڵخانە", ar: "قنصلية", en: "Consulate" }, aliases: ["consulate", "کونسوڵخانە", "قنصلية"] },
  { id: "windmill", group: "tourism_nature_heritage", label: { ku: "ئاشی با", ar: "طاحونة هوائية", en: "Windmill" }, aliases: ["windmill", "ئاشی با", "طاحونة هوائية"] },
  { id: "general_store", group: "retail_commerce", label: { ku: "فرۆشگای گشتی", ar: "متجر عام", en: "General store" }, aliases: ["general store", "general shop", "فرۆشگای گشتی", "متجر عام"] },
  { id: "nightclub", group: "sports_leisure", label: { ku: "یانەی شەوانە", ar: "ملهى ليلي", en: "Nightclub" }, aliases: ["nightclub", "night club", "یانەی شەوانە", "ملهى ليلي"] },
  { id: "vending_machine", group: "retail_commerce", label: { ku: "ئامێری فرۆشتنی خۆکار", ar: "آلة بيع", en: "Vending machine" }, aliases: ["vending machine", "ئامێری فرۆشتنی خۆکار", "آلة بيع"] },
  { id: "water_mill", group: "tourism_nature_heritage", label: { ku: "ئاشی ئاو", ar: "طاحونة مائية", en: "Water mill" }, aliases: ["water mill", "watermill", "ئاشی ئاو", "طاحونة مائية"] },
  { id: "post_box", group: "transport_logistics", label: { ku: "سندوقی پۆست", ar: "صندوق بريد", en: "Post box" }, aliases: ["post box", "mail box", "سندوقی پۆست", "صندوق بريد"] },
  { id: "hunting_stand", group: "tourism_nature_heritage", label: { ku: "شوێنی چاودێری ڕاو", ar: "منصة صيد", en: "Hunting stand" }, aliases: ["hunting stand", "شوێنی چاودێری ڕاو", "منصة صيد"] },
  { id: "lighthouse", group: "transport_logistics", label: { ku: "فانۆسی دەریایی", ar: "منارة بحرية", en: "Lighthouse" }, aliases: ["lighthouse", "فانۆسی دەریایی", "منارة بحرية"] },
  { id: "beer_garden", group: "food_hospitality", label: { ku: "باخی بار", ar: "حديقة حانة", en: "Beer garden" }, aliases: ["beer garden", "biergarten", "باخی بار", "حديقة حانة"] },
  { id: "battlefield", group: "tourism_nature_heritage", label: { ku: "گۆڕەپانی جەنگ", ar: "ساحة معركة", en: "Battlefield" }, aliases: ["battlefield", "گۆڕەپانی جەنگ", "ساحة معركة"] },
  { id: "newsagent", group: "retail_commerce", label: { ku: "فرۆشگای ڕۆژنامە", ar: "بائع صحف", en: "Newsagent" }, aliases: ["newsagent", "news stand", "فرۆشگای ڕۆژنامە", "بائع صحف"] },
  { id: "bicycle_rental", group: "transport_logistics", label: { ku: "کرێی پاسکیل", ar: "تأجير دراجات", en: "Bicycle rental" }, aliases: ["bicycle rental", "bike rental", "کرێی پاسکیل", "تأجير دراجات"] },
  { id: "embassy", group: "government_public", label: { ku: "باڵیۆزخانە", ar: "سفارة", en: "Embassy" }, aliases: ["embassy", "باڵیۆزخانە", "سفارة"] },
  { id: "car_sharing", group: "transport_logistics", label: { ku: "هاوبەشی ئۆتۆمبیل", ar: "مشاركة سيارات", en: "Car sharing" }, aliases: ["car sharing", "car_sharing", "هاوبەشی ئۆتۆمبیل", "مشاركة سيارات"] },
  { id: "ice_rink", group: "sports_leisure", label: { ku: "مەیدانی سەرما", ar: "حلبة تزلج", en: "Ice rink" }, aliases: ["ice rink", "ice_rink", "مەیدانی سەرما", "حلبة تزلج"] },
  { id: "historic", group: "tourism_nature_heritage", label: { ku: "مێژوویی", ar: "تاريخي", en: "Historic site" }, aliases: ["historic", "historical", "مێژوویی", "تاريخي"] },
  { id: "nature", group: "tourism_nature_heritage", label: { ku: "سروشت", ar: "طبيعة", en: "Nature" }, aliases: ["nature", "natural", "سروشت", "طبيعة"] },
  { id: "tourism", group: "tourism_nature_heritage", label: { ku: "گەشتیاری", ar: "سياحة", en: "Tourism" }, aliases: ["tourism", "tourist", "گەشتیاری", "سياحة"] },
  { id: "religious", group: "culture_religion_media", label: { ku: "شوێنی ئایینی", ar: "مكان ديني", en: "Religious place" }, aliases: ["religious", "religion", "شوێنی ئایینی", "مكان ديني"] },
  { id: "cultural", group: "culture_religion_media", label: { ku: "شوێنی کولتووری", ar: "مكان ثقافي", en: "Cultural place" }, aliases: ["cultural", "culture", "شوێنی کولتووری", "مكان ثقافي"] },
  { id: "airport_apron", group: "transport_logistics", label: { ku: "مەیدانی وەستانی فڕۆکە", ar: "ساحة وقوف الطائرات", en: "Airport apron" }, aliases: ["airport apron", "apron", "ساحة وقوف الطائرات", "مەیدانی وەستانی فڕۆکە"] },
  { id: "speed_camera", group: "emergency_security", label: { ku: "کامێرای خێرایی", ar: "رادار سرعة", en: "Speed camera" }, aliases: ["speed camera", "radar", "رادار سرعة", "کامێرای خێرایی"] },
  { id: "traffic_signal", group: "border_route", label: { ku: "ئیشارەی هاتوچۆ", ar: "إشارة مرور", en: "Traffic signal" }, aliases: ["traffic signal", "traffic light", "إشارة مرور", "ئیشارەی هاتوچۆ"] },
  { id: "pedestrian_crossing", group: "border_route", label: { ku: "پەڕینەوەی پیادە", ar: "معبر مشاة", en: "Pedestrian crossing" }, aliases: ["pedestrian crossing", "crosswalk", "معبر مشاة", "پەڕینەوەی پیادە"] },
  { id: "turning_circle", group: "border_route", label: { ku: "بازنەی سوڕانەوە", ar: "دائرة دوران", en: "Turning circle" }, aliases: ["turning circle", "دائرة دوران", "بازنەی سوڕانەوە"] },
  { id: "motorway_junction", group: "border_route", label: { ku: "دووڕێی ئۆتۆستراد", ar: "تقاطع طريق سريع", en: "Motorway junction" }, aliases: ["motorway junction", "highway junction", "تقاطع طريق سريع", "دووڕێی ئۆتۆستراد"] },
  { id: "railway_crossing", group: "border_route", label: { ku: "پەڕینەوەی شەمەندەفەر", ar: "معبر سكة حديد", en: "Railway crossing" }, aliases: ["railway crossing", "level crossing", "معبر سكة حديد", "پەڕینەوەی شەمەندەفەر"] },
  { id: "other", group: "government_public", label: { ku: "شوێنی تر", ar: "مكان آخر", en: "Other place" }, aliases: ["other", "place", "شوێنی تر", "مكان آخر"] },
] as const satisfies readonly AtlasTaxonomyEntry[];

export type AtlasPlaceTypeId = (typeof ATLAS_TAXONOMY)[number]["id"];


const ENTRY_BY_ID = new Map<string, AtlasTaxonomyEntry>(ATLAS_TAXONOMY.map((entry) => [entry.id, entry]));
const GROUP_BY_ID = new Map<string, AtlasTaxonomyGroup>(ATLAS_TAXONOMY_GROUPS.map((group) => [group.id, group]));

export function atlasTaxonomyEntry(id: unknown): AtlasTaxonomyEntry | undefined {
  return typeof id === "string" ? ENTRY_BY_ID.get(id.trim().toLocaleLowerCase("en-US").replace(/[\s-]+/g, "_")) : undefined;
}

export function atlasTaxonomyGroup(id: unknown): AtlasTaxonomyGroup | undefined {
  return typeof id === "string" ? GROUP_BY_ID.get(id.trim()) : undefined;
}

export function atlasPlaceTypeLabel(id: unknown, language: Language): string {
  return atlasTaxonomyEntry(id)?.label[language] ?? "";
}

export function atlasPlaceTypeSections(id: unknown): readonly AtlasEditorSection[] {
  const entry = atlasTaxonomyEntry(id);
  return entry ? (atlasTaxonomyGroup(entry.group)?.sections ?? []) : [];
}

export function atlasPlaceTypeGroup(id: unknown): string {
  return atlasTaxonomyEntry(id)?.group ?? "";
}

export function atlasPlaceTypeSearchTerms(id: unknown): readonly string[] {
  return atlasTaxonomyEntry(id)?.aliases ?? [];
}
